### ISSUE TITLE
staticcheck: passing typed nil as function args that are an interface

### ISSUE THREAD

**Issue by sina-devel** [dominikh/go-tools#1015]
```go
type Foo struct {
	bar string
}

func (f *Foo) String() string {
	return f.bar
}

func Println(s fmt.Stringer) {
	if s == nil {
		// doesn't works when s is a typed nil
		fmt.Println(nil)
	}
	fmt.Println(s.String())
}

func main() {
	Println(nil)
	var f *Foo 
	Println(f)
}
```

**Comment by dominikh** [comment]
This isn't something we can flag without false positives. There is nothing inherently wrong about passing typed nils to the function; consider https://play.golang.org/p/gmpl51yI7EE:

```
package main

import "fmt"

type Foo struct{}

func (*Foo) String() string {
	return "Hello, world"
}

func Println(s fmt.Stringer) {
	fmt.Println(s.String())
}

func main() {
	var f *Foo
	Println(f)
}
```

We could attempt more advanced analysis to detect nil pointer dereferences, but this generally runs the risk of false positives, too, due to infeasible paths and correlated variables (there are various existing issues for this.)
