### ISSUE TITLE
check for: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 89z** [dominikh/go-tools#1035]
Someone asked this question online [1], so I am repeating here. Using this example:

~~~go
package main
import "fmt"

type s struct {
   n *int
}

func main() {
   var v s
   fmt.Println(*v.n)
}
~~~

if you build it, no problem, but if you run it:

~~~
invalid memory address or nil pointer dereference
~~~

does this tool have someway to check for that?

1. https://stackoverflow.com/questions/67952200

**Comment by dominikh** [comment]
Detecting all nil pointer dereferences is impossible without false positives, and we don't generally tolerate false positives. It would also be fairly expensive to compute.

Detecting trivial nil pointer dereferences like this one isn't worth it, because even with minor additions to the code they would no longer be easy to detect.

We do have [SA5011](https://staticcheck.io/docs/checks#SA5011) which flags a specific kind of potential nil pointer dereference, though this wouldn't help with your example.
