### ISSUE TITLE
staticcheck: "argument should be pointer-like to avoid allocations (SA6002)"

### ISSUE THREAD

**Issue by spiritedfang** [dominikh/go-tools#1042]
**Description**

When preallocating a sync.Pool with N M-sized buffers, "argument should be pointer-like to avoid allocations (SA6002)" comes up as a warning. It feels like it definitely shouldn't be pointer-like when I'm purposefully trying to allocate buffers? Maybe I'm doing something wrong here? Thanks!

```go
package main

import (
	"sync"
)

func main() {
	m, n := 4096, 500
	buffers := new(sync.Pool)
	buffers.New = func() interface{} { return make([]byte, m) }
	for i := 0; i < n; i++ { 
		buffers.Put(make([]byte, m)) // <-- SA6002
	}
}
```

**Version**

- go version go1.16.3 windows/amd64
- staticcheck 2021.1 (v0.2.0), Compiled with Go version: go1.16.3

**Comment by spiritedfang** [comment]
Interestingly, the following doesn't throw warnings:

```go
package main

import (
	"sync"
)

func main() {
	m, n := 4096, 500
	buffers := new(sync.Pool)
	buffers.New = func() interface{} { return make([]byte, m) }
	for i := 0; i < n; i++ {
		buffers.Put(buffers.New())
	}
}
```

**Comment by dominikh** [comment]
Please see https://staticcheck.io/docs/checks#SA6002 and specifically Dmitry Vyukov's comments in https://go-review.googlesource.com/c/go/+/24371 and let me know if that clears things up.

**Comment by spiritedfang** [comment]
Hi @dominikh! Thanks for the prompt reply. Dmitry's example does help for a dynamic buffer, but I still don't think the warning makes sense for preallocated fixed-length buffers (receiving bytes from a net.Conn). Maybe I'm missing something?

**Comment by dominikh** [comment]
The issue is that sync.Pool.Put takes an interface value. An interface value is a pair of pointers, one to a type and one to the data. If the concrete value is already a pointer, it can be stored in an interface value directly. Otherwise, we need to allocate memory on the heap, store the value there, and store the pointer to the value in the interface value.

A slice is not a pointer (it is a struct consisting of 3 fields). 

Thus, in the common pattern of

```
b := pool.Get().([]byte)
...
pool.Put(b)
```

the pool.Put needs to allocate to put `b` in the `interface{}`. If, instead, we had pointers to slices, no allocation on the call to `Put` would be needed.

**Comment by spiritedfang** [comment]
Ahhh, ok. I think I understand it now. Thanks for the explanation!
