### ISSUE TITLE
gosimple: suggest iotas

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#11]
Some cases I've encountered inside `const ( )`:

```
Foo = 0
Bar = 1
Etc = 2
```

could be

```
Foo = iota
Bar
Etc
```

And:

```
Foo Type = 1
Bar Type = 2
Etc Type = 3
```

could be

```
_ Type = iota
Foo
Bar
Etc
```

Could also apply to more complex operations like shifts, but these would already be very useful.

**Comment by mvdan** [comment]
To clarify, this covers:

* Using `iota` directly with no operation
* Typed constants as well as untyped ones
* Discarding N initial iota values

**Comment by bradleyfalzon** [comment]
I think this might create too many false positives, as often I've defined constants without iota when they need to exactly match some external definition.

A non-perfect example: https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/syscall/ztypes_windows.go#L32-L36

**Comment by mvdan** [comment]
The tool needs to check that the actual integer values wouldn't change. In that case, there is no space for false positives.

**Comment by dominikh** [comment]
This is not a suggestion we can make. `iota` is for enum-style constants where the specific values do not matter. However, if you're adding constants that should match an external API, you want to be explicit with your values (even if they could be expressed with an iota). The use of explicit values makes it clear that they have a meaning, and that, for example, one can't add a new constant in the middle of the run.

See for example https://golang.org/pkg/io/#pkg-constants for an application of this rule.

BTW, instead of `_ = iota` you could say `Foo = iota + 1`

**Comment by mvdan** [comment]
Ah, fair enough. This is unfortunate because I've seen too many people reproduce iotas manually.
