### ISSUE TITLE
Import cycles in tests lead to weird errors

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#1127]
```
-- go.mod --
module example.com/sand2

go 1.17
-- sand.go --
package pkg

import (
	_ "bytes"
)
-- sand_test.go --
package pkg

import (
	_ "example.com/sand2"
)
```

```
 $ run-dev-staticcheck 
-: # example.com/sand2 [example.com/sand2.test]
./sand.go:4:2: could not import "bytes": open : no such file or directory
# example.com/sand2 [example.com/sand2.test]
./sand.go:4:2: could not import "bytes": open : no such file or directory (compile)
```

**Comment by qyanggit** [comment]
Any update on this issue?
I am seeing the same error message 'could not import "bytes": open : no such file or directory' when I tried to compile my service. I see the error occurs as soon as I included a test file. Without that test file, this error doesn't show up. 
Is this because of import cycle introduced by that particular test file?

**Comment by dominikh** [comment]
You can determine if this is caused by a cycle in the tests by trying to compile the tests.

**Comment by dominikh** [comment]
Does no longer reproduce on master.
