### ISSUE TITLE
Can we exclude "`I`" from `ST1005`?

### ISSUE THREAD

**Issue by frederikhors** [dominikh/go-tools#1128]
I'm getting `ST1005: error strings should not be capitalized (stylecheck)` for this code:

```go
var ErrCannotRetrieveItemNow = errors.New("I cannot retrieve item now")
```

I think we should exclude "`I`" from this, right?

**Comment by dominikh** [comment]
In theory? Yes. In practice? Unless this is a text-based role-playing game, there should be no "I" in that error message. The computer/program/function executing the code isn't a person and that error message isn't idiomatic.

**Comment by frederikhors** [comment]
How to answer then? Without "I"?

**Comment by dominikh** [comment]
Without knowing the specifics of the API, I would say one of these:
- `couldn't retrieve item` if you tried to retrieve the item and failed. The action is in the past, and the time is implied, it just happened.
- `cannot retrieve item` if you know a priori that the item cannot be retrieved, for no specific reason
-  `cannot retrieve item at this time` if the reason the item cannot be retrieved is because it's now
-  `cannot retrieve item yet` if it's because it's now, not later (say, we require some task to finish first)
