### ISSUE TITLE
Cycles dependency - build fail

### ISSUE THREAD

**Issue by Pro-pra** [dominikh/go-tools#1156]
Have nice day!
Build go-tools requres x-tools pkg for build, x-tools pkg requires go-tools pkg for build :(

With builded tools pkg, build go-tools fail with error:
```
+ go build -buildmode pie -compiler gc '-tags=rpm_crashtraceback ' -ldflags ' -X honnef.co/go/tools/version=2021.1.2 -X honnef.co/go/tools/version.tag=2021.1.2 -B 0x87d9c9cd59a0343f63aae618380d78d6fd2ac6af -compressdwarf=false -extldflags '\''-O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic -Wl,-O2  -Wl,--no-undefined   '\''' -a -v -x -o /builddir/build/BUILD/go-tools-2021.1.2/_build/bin/keyify honnef.co/go/tools/cmd/keyify
WORK=/tmp/go-build1664483489
package honnef.co/go/tools/cmd/keyify
	imports golang.org/x/tools/go/loader
	imports honnef.co/go/tools/config
	imports golang.org/x/tools/go/analysis
	imports golang.org/x/tools/internal/analysisinternal
	imports golang.org/x/tools/go/ast/astutil
	imports golang.org/x/tools/go/ast/astutil: import cycle not allowed
```

astutil need go-tools? Help me solve this circular dependency.

**Comment by dominikh** [comment]
Your output looks highly inconsistent with the actual code, both mine and that in x/tools. `golang.org/x/tools/go/loader` does not, in fact, import `honnef.co/go/tools/config`. Also, your error ultimately claims that `golang.org/x/tools/go/ast/astutil` imports itself, which is also not true.

I don't know what you did to find yourself in this state, but as far as I can tell, it isn't due to our code.
