### ISSUE TITLE
Staticcheck: Provide CLI option to precise configuration file path 

### ISSUE THREAD

**Issue by SamuelCabralCruz** [dominikh/go-tools#1157]
This is a feature request.

It would be nice to be able to have an CLI option for providing a path to a configuration file to be used as default configuration.
This would avoid to pollute root folder with configuration and regroup everything under a subfolder.

**Comment by dominikh** [comment]
Staticcheck doesn't use a single configuration file, but a [tree of files](https://staticcheck.io/docs/configuration/#configuration-files). With that in mind, I don't think that such a flag would make sense because its semantics wouldn't be obvious. Would the flag disable all nested configuration files? Would it specify just the root configuration? If the current working directory is in a subpackage, would the flag specify the configuration for that subtree, or for the root? In all of these cases, the flag would lead to special treatment that differs from how our configuration files normally work.
