### ISSUE TITLE
Bug: "type XXX is unused" with generics param as slice

### ISSUE THREAD

**Issue by matheusoliveira** [dominikh/go-tools#1289]
Hi all,

I believe I found a very small bug on staticcheck that complains about unused type when it is actually used as slice parameter of a generic type (doesn't complain when used without the slice).

Minimal code example (file named as `test.go`):

```go
package main

func main() {
	type Foo[T any] struct {
		Id int `json:"id"`
		Data T `json:"data"`
	}
	type Bar struct {
		X int `json:"x"`
		Y int `json:"y"`
	}
	v := Foo[[]Bar]{}
	_ = v // just use it, but could be some json.Unmarshal, for instance
}
```

Result:
```sh
$ staticcheck ./...
test.go:8:7: type Bar is unused (U1000)
```
Versions:
```sh
$ go version
go version go1.18 linux/amd64

$ staticcheck -version
staticcheck 2022.1.2 (v0.3.2)

$ staticcheck -debug.version
staticcheck 2022.1.2 (v0.3.2)

Compiled with Go version: go1.18
Main module:
	honnef.co/go/tools@v0.3.2 (sum: h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=)
Dependencies:
	github.com/BurntSushi/toml@v0.4.1 (sum: h1:GaI7EiDXDRfa8VshkTj7Fym7ha+y8/XxIgD2okUIjLw=)
	golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e (sum: h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=)
	golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 (sum: h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=)
	golang.org/x/sys@v0.0.0-20211019181941-9d821ace8654 (sum: h1:id054HUawV2/6IGm2IV8KZQjqtwAOo2CYlOToYqa0d0=)
	golang.org/x/tools@v0.1.11-0.20220513221640-090b14e8501f (sum: h1:OKYpQQVE3DKSc3r3zHVzq46vq5YH7x8xpR3/k9ixmUg=)
```

Few points:
- works if you use `Foo[Bar]` instead of `Foo[[]Bar]`
- works if the types are declared outside a function

Thanks for your attention and for this very nice tool.

**Comment by dominikh** [comment]
Interesting.

Note that this behaves correctly on `master`, albeit by accident, via 97b99f31cd05807b26c27b8287035af5db706e0c. That change hasn't been backported to a patch release because it depends on other non-bugfix changes and wasn't expected to fix any existing bugs.

At this point I'm in the middle of a rewrite of `unused`, which will be part of the next feature release, which will roughly coincide with the release of Go 1.19. In other words, you'll have to use one of the workarounds (or [`//lint:ignore`](https://staticcheck.io/docs/configuration/#ignoring-problems)) for now, and this will be fixed in the next feature release.

**Comment by dominikh** [comment]
Although a similar bug does exist at master; this code still marks `Bar` as unused:

```
func main() {
	type Foo[T any] struct{}
	type Bar struct{}
	v := Foo[[]Bar]{}
	_ = v // just use it, but could be some json.Unmarshal, for instance
}
```
