### ISSUE TITLE
How to extend staticcheck to detect incomplete Gomega TDD assertions?

### ISSUE THREAD

**Issue by thediveo** [dominikh/go-tools#1305]
[Gomega](https://onsi.github.io/gomega/) is an assertion plus matcher Go module, where assertions might look like this:

```go
Expect(foos).To(ContainElement("bar"))
```

As it happens, Gomega users might from time to time make the mistake to not complete their assertions, for instance:

```go
Expect(foos) // valid Go
```

While not completely impossible to detect this at runtime, it would need a tight coupling between Gomega and whatever BDD/TDD harness is used -- something that should be avoided.

However, linting looks like a good place to catch such mistakes early. Thus, I would like to explore if and how `staticcheck` can be extended to lint assertions with the prospect to maybe extend it in the future to also catch typical subtle mistakes in asynchronous assertions.

1. would the `staticcheck` project even accept PRs to extend `staticcheck` with linting checks related to "custom" assertion libraries that aren't part of Go's standard library?
2. is there any documentation what the extension points in `staticcheck` are, even if they are currently rather implicit?

Any advice is greatly appreciated!

**Comment by dominikh** [comment]
> would the staticcheck project even accept PRs to extend staticcheck with linting checks related to "custom" assertion libraries that aren't part of Go's standard library?

I'm not opposed to checks for third party libraries, as long as
- the library is sufficiently popular (which seems to be the case for Gomega)
- the checks aren't opinionated, don't have false positives and are in line with what upstream thinks is right
- they don't introduce any new dependencies to Staticcheck

> is there any documentation what the extension points in staticcheck are, even if they are currently rather implicit?

There isn't at the moment, no. Staticcheck's checks are implemented in the `staticcheck`, `simple`, and `stylecheck` packages, mapping to the SA, S and ST categories of checks respectively. You would have to peruse their code to see how to implement such a check. A general understanding of static analysis in Go would be beneficial. To flag free-standing calls to `Expect` you'll need to inspect the AST as well as make use of type information.

**Comment by dominikh** [comment]
I do have a (_very_) work in progress document describing the overall structure of the project. It's rather incomplete, but may contain some useful information. You can find a copy at https://gist.github.com/dominikh/0a4f4af6b0382b97cd8a2a0f9ef8fd19.

**Comment by dominikh** [comment]
Alternatively you might be interested in implementing this outside of Staticcheck, in which case https://github.com/quasilyte/go-ruleguard or https://semgrep.dev/ might prove useful. These tools are explicitly designed to let you write your own checks.

**Comment by thediveo** [comment]
I highly appreciate the pointers to other linting projects! After looking more into them, here are my impressions:
- semgrep has IMHO several disadvantages: it requires a lot of Python stuff to be installed. While I have fond memories of realizing several projects in Python, installing it even into containers is a constant pain and resource hog. Also, semgrep tries to be a one-stop-shop for everyone which I most of the time dislike, as it gives rather poor results.
- go-ruleguard looks quite promising, but unfortunately doesn't seem to be integrated into vscode and golangci-lint, which is probably due to itss very nature of mostly being a building block. I like the idea of AST-level "pattern matching". But deployment is a pain outside your very own maintained CI. It's nothing to get golang+Gomega users hassle-free up and running.

As for a potential add-on to staticcheck and avoiding dependencies: any idea how I can avoid Gomega dependencies due to the unit tests to check the AST checkers, or would be indirect test dependencies acceptable?

What is the general pattern to check that a function call is followed by a certain other chained receiver call?

**Comment by dominikh** [comment]
> how I can avoid Gomega dependencies due to the unit tests to check the AST checkers

You can create a mock package that imitates the relevant parts of Gomega's API. See for example `staticcheck/testdata/src/github.com/jessevdk/go-flags`, which is used by `staticcheck/testdata/src/CheckStructTags/CheckStructTags.go`.

> What is the general pattern to check that a function call is followed by a certain other chained receiver call?

If you want to check that `Foo(...)` is always followed by another call, then you'll want to invert the problem. Look for free-standing calls of Foo and flag those. These would be top-level statements in ast.BlockStmt.

Note that checking "is followed by a certain other chained receiver call" on the AST is not sufficient. To avoid false positives you also have to consider that the first function call's return value can be stored in a variable and used later, or passed to a function (among other ways of using values in Go). Even if those aren't idiomatic uses of Gomega, they're semantically valid and shouldn't get flagged. That's why we look for invalid uses; we don't try to prove that uses are valid.

You could write a much more complex analysis to find more invalid uses in these instances, but that would entail data flow analysis and is far outside the scope for someone's first static analysis.

If you want to check that `Foo(...)` is never followed by a certain other call (e.g. because `Foo().Bar()` is invalid), then the easiest approach would be to use Staticcheck's pattern matching code to look for exactly that pattern. This would entail false positives for much the same reason as the false positives above, with much the same solutions.

**Comment by dominikh** [comment]
On a related note, Staticcheck already has [SA4017](https://staticcheck.io/docs/checks/#SA4017) which flags pointless calls to pure functions. It uses a combination of a hardcoded list of pure functions (e.g. fmt.Sprintf) and detection of trivially pure functions. It might be sufficient to add some of Gomega's functions to the list of known pure functions? You can find that in `analysis/facts/purity/purity.go`

**Comment by thediveo** [comment]
I'll look into SA4017 ... albeit the irony is that the final call in an assertion is returning a mostly pointless bool that normally gets ignored 🤷🏼
