### ISSUE TITLE
Wrong help message in `SA1019: rand.Seed has been deprecated since Go 1.20`

### ISSUE THREAD

**Issue by qdm12** [dominikh/go-tools#1374]
In the reported error text below, `NewRand(NewSource(seed))` should be `rand.New(rand.NewSource(seed))` since `NewRand` does not exist on import `math/rand`. I thought adding `rand.` prefixes to calls would clarify from which package we call `New` and `NewSource`.

> SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.

I tried forking, cloning and digging in the code but couldn't find really where this string message is coming from unfortunately.

**Comment by dominikh** [comment]
We are reporting exactly the deprecation message that Go provides: https://pkg.go.dev/math/rand#Seed. Mistakes (NewRand does indeed not exist) in that message need to be fixed in Go.

We're not going to modify the provided message to turn unqualified identifiers into qualified ones; that would be error-prone.
