### ISSUE TITLE
Bump golang.org/x/tools to v0.7.0 (as minimum) and make new tag

### ISSUE THREAD

**Issue by Antonboom** [dominikh/go-tools#1383]
Hi 🙂

Please, bump `golang.org/x/tools` to v0.7.0 (as minimum) and make new tag in your repo.

It's important to support new 1.20 **golangci-lint.**
Related to https://github.com/golangci/golangci-lint/issues/3086

Thanks!

P.S. Optionally I recommend

- [ ] to move linter to 1.20 totally (go.mod, CI, etc.)
- [ ] add support of [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

**Comment by dominikh** [comment]
https://github.com/golangci/golangci-lint/issues/3086 seems to be an issue with golang.org/x/tools/go/ssa, which we do not use. Also, our version of golang.org/x/tools doesn't matter to golangci-lint, their go.mod controls the versions of all dependencies.

> to move linter to 1.20 totally (go.mod, CI, etc.)

Releases support the last two versions of Go. Therefore we explicitly limit ourselves to the Go 1.19 language. You're right that CI should run on Go 1.20, *in addition to Go 1.19, not instead of.*

> add support of [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

No thanks. We update dependencies consciously, i.e. when they contain changes that matter to us.

We currently use v0.6.1-0.20230305040040-c0742f584bb2 which, compared to v0.7.0 only contains the following changes:

```
031fc7596 (tag: v0.7.0) gopls/internal/regtest/bench: don't run the iwl test with -short
f477bf4a4 gopls/internal/lsp/source/completion: avoid Snapshot.CachedPackages
b72edd12e gopls/internal/lsp/filecache: GOPLS_CACHE -> GOPLSCACHE
d56692763 gopls/internal/lsp/regtest: add @suggestedfix marker
fdb0da65a gopls/internal/regtest/bench: add a benchmark for diagnosing a change
6eb432f3b gopls/internal/regtest/bench: add benchmarks in a wider variety of repos
c91d0b88c gopls/internal/lsp/source: guard against concurrent writes in xrefs
```

That is, even if the go/ssa issue affected us, we'd already be on a new enough version of x/tools.

On a personal note: I see that you've opened the same issue on a dozen dependencies of golangci-lint, even on projects that do not use go/ssa, or even depend on x/tools at all. You're causing a lot of unnecessary work for a lot of people. I'm sure you had good intentions, but this isn't the way to do it, especially when the fix would've been a one-line change in golangci-lint itself.

**Comment by Antonboom** [comment]
@dominikh, thank u for expand answer!

> Also, our version of golang.org/x/tools doesn't matter to golangci-lint, their go.mod controls the versions of all dependencies

It depends on result of [MVS](https://go.dev/ref/mod#minimal-version-selection).
But you are right, recently `golangci-lint` uses x/tools` v0.7.0 (was derived from one of updated dependency).

> even on projects that do not use go/ssa, or even depend on x/tools at all
> ...
> especially when the fix would've been a one-line change in golangci-lint itself.

Yes, sorry, it's my bad. I was definitely thinking the same way, but the local experiments looks like black magic – I receive different results with different variations of 
- golangci-lint x/tools/ssa
- specific linter x/tools/ssa

And I collected the strange set of "broken" linters 🤔.
I think there is some mess of different problems here. Maybe cache? Or ...?

I went through the list again and commented on the linters that don't use `buildssa.Analyzer`.
I think in any case it is useful for authors to pay attention to their ancient projects, it takes a couple of minutes.

About Go version, deps and bots – it's absolutely your kitchen and choice, no problems 👍 

> I'm sure you had good intentions, but this isn't the way to do it

If you know about root of evil – please, feel free to contribute in `golangci-lint`.
I'm just trying to do something while others are waiting for the problem to go away on its own.

Thanks again.

**Comment by dominikh** [comment]
> It depends on result of [MVS](https://go.dev/ref/mod#minimal-version-selection).

golangci-lint is part of the dependency graph. It can choose to depend on x/tools at v0.7.0. This will force all dependencies to also use v0.7.0 – the entire program gets compiled with a single (minor/patch) version of a dependency. MVS selects the smallest possible version, which can't be lower than any of the specified versions.

golangci-lint thus didn't have to wait for any dependency to select a higher version. This even works for purely transitive dependencies, but in this case, golangci-lint directly depends on x/tools, anyway.
