### ISSUE TITLE
Unused function parameters

### ISSUE THREAD

**Issue by JeremyCraven** [dominikh/go-tools#1501]
Currently, gopls is catching unused parameters in functions. I want to enforce this in staticcheck as well as that is part of our CI. Running staticcheck does not catch anything on the same code that gopls catches `unusedparams` (https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/unusedparams#unusedparam)

I searched through the documentation and this is the closest I found to possibly what I'm looking for (https://github.com/dominikh/go-tools/issues/1475). It seems this analyzer is part of staticcheck by default and on so maybe it doesn't work for my use case.

Any suggestions or something I've missed to allow me to catch these unused function parameters with staticcheck?

go version: 1.21.3
gopls version: v0.15.1
staticcheck version: 2023.1.7

**Comment by dominikh** [comment]
I believe this would be #124, but I don't have any plans of working on this in the short term.

You have two easy alternatives:

1. You can run `golang.org/x/tools/gopls/internal/analysis/unusedparams/cmd`, which is the standalone version of `unusedparam` from gopls
2. You can build a custom version of Staticcheck that includes the unusedparams check. To do so, you would patch https://github.com/dominikh/go-tools/blob/0a683c983d783468a36cacffe289440ea4b7b943/cmd/staticcheck/staticcheck.go#L31 and add a call like `cmd.AddBareAnalyzers(unusedparams.Analyzer)`

Unfortunately, the second option isn't as viable, because the `unusedparams` analyzer is an `internal` package and cannot be imported. The first option, on the other hand, is trivial, since you could just use `go run golang.org/x/tools/gopls/internal/analysis/unusedparams/cmd@latest ./...`.
