### ISSUE TITLE
staticcheck: remove SA1022 (flag.Usage + os.Exit)

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#159]
Both Rob Pike and Russ Cox regularly call os.Exit in usage functions and have argued that this is okay (see for example https://github.com/rsc/getopt/commit/9e2cef26fc2691a8d9b2bb4a3ff7d5db4fe89f82#commitcomment-23601620)

It seems unwise to disagree with two members of the Go team, one of which authored the flag package.

/cc @shurcooL

**Comment by mvdan** [comment]
Dmitri and I discussed this here: https://dmitri.shuralyov.com/issues/dmitri.shuralyov.com/idiomatic-go/1

I agree with him, but I don't feel very strongly about it since it's a correctness issue that is unlikely to affect program behavior. I still think this check should stay, though.

**Comment by shurcooL** [comment]
Thanks for pointing to relevant discussion @mvdan.

I've considered Russ's points, and after consideration, decided to try to put together an argument for why I disagree at https://github.com/mdempsky/unconvert/commit/3b9aa41c71a855a5f5fee96dc751979ce6e8cbbe#commitcomment-23726997.

As far as this SA1022 check goes, I still think it's correct and valid. However, without certainty about whether it's worthwhile fixing (caused by two members of the Go team not thinking its important), I think it'd be fine for your tool to remove it, because it may not add value. A check adds value when it points out issues that people think are worth fixing.

I'm fine (but slightly sad) with it being removed if you think that's the better tradeoff.

**Comment by dominikh** [comment]
Based on what Russ said, maybe we should limit this check to exported functions?

**Comment by shurcooL** [comment]
Can you be more specific about what you mean by exported functions? `flag.Usage` is exported.

**Comment by dominikh** [comment]
Functions assigned to flag.Usage may be exported or unexported. As Russ puts it, unexported functions don't need to abide by some external contract or anticipate different configurations of `flag`. That is, it is fine for them to os.Exit. 

Exported functions, however, can be used from other packages by other users and should behave in accordance with `flag`'s configuration.

**Comment by shurcooL** [comment]
> Exported functions, however, can be used from other packages by other users and should behave in accordance with `flag`'s configuration.

Not if they're in `package main`:

```Go
Package main

// MyUsage is exported, but in package main.
// It cannot be used by other packages.
func MyUsage() { ... }

func main()
    flag.Usage = MyUsage
    flag.Parse()

    ...
}
```

If you mean exported _and_ in non-main package, that sounds reasonable.

**Comment by dominikh** [comment]
Good point, we'd have to special case `main`. And yes, that's now what I mean.

**Comment by dominikh** [comment]
Per https://github.com/golang/go/issues/21540#issuecomment-323854615 I will most likely disable the check entirely.

**Comment by dominikh** [comment]
Final nail in the coffin: https://github.com/golang/go/issues/21671
