### ISSUE TITLE
gosimple: rebrand as tool for editors, not CI

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#180]
People use gosimple in CI, effectively treating its output as gospel. That limits us in two, related ways: 1) We can only make suggestions that everybody can agree on. That is, the new code has to be objectively better. 2) We cannot offer any code transformations that are neither better nor worse, but are purely subjective choice. 

Especially issue 2 is a feature common in editors: quickfixes like changing boolean expressions to read differently (but not necessarily better), alternating between if/else if and switch statements, alternating between Sprintf and string concatenation, and so on.

I believe that gosimple would be a lot more useful if it provided subjective code rewrites in editors. 

I've never quite liked gosimple in CI, because at the end of the day it mostly produces churn on otherwise good code. However, there is an argument to be made in favour of objectively simpler code, so we may split gosimple into two parts: objective checks that can be run in CI, and all other code transformations for editors. We'd guard the second group of checks behind a CLI flag that editors have to use.

Related: #144, https://github.com/dominikh/go-staticcheck/issues/63

/cc @bradleyfalzon, @shurcooL and everybody else who has valuable input

**Comment by shurcooL** [comment]
I think this is the same (or related) as #91.

As far as feedback goes, I have some. I believe there's a nice middle ground between editors and CI. I found it out of necessity.

I don't want to run `gosimple` and `unused` in CI and fail a build if there's at least one entry reported. At the same time, I don't have great editor integration/support in GoSublime. So I've started a practice of running a local CI alias before merging commits to `master` (which then causes Travis CI to run real CI on `master`).

My local CI alias is a superset of the remote CI script. It has the benefit of letting me, a human, use my judgement before pushing. If any of these tools report an issue (usually they don't), I consider the suggestion and deal with it appropriately (either fix it, or ignore it, depending on what's best at the time) before pushing to the remote.

I imagine I still wouldn't want to see optional suggestions (because I'd have to keep ignoring them), and those should still be limited to editors behind an opt-in flag.

**Comment by dominikh** [comment]
go/analysis may be getting support for reporting code fixes, at which point it should be straightforward to integrate with gopls.

**Comment by dominikh** [comment]
Closing in favour of https://github.com/dominikh/go-tools/issues/474 – we'll split gosimple into two categories, one of which will only be used in the context of editors (via gopls or via CLI flags for editors that shell out to staticcheck.)
