### ISSUE TITLE
quickfix: detect math.Pow() with small positive constants

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#181]
(Copied from https://github.com/dominikh/go-staticcheck/issues/63, originally by @dgryski)

https://github.com/golang/go/issues/7416

`math.Pow(x,1)`, and `math.Pow(x,2)` should definitely be flagged.

`math.Pow(x,3)` and `math.Pow(x,4)` maybe ?

Where to draw the line?

**Comment by dominikh** [comment]
Related: #180

**Comment by shurcooL** [comment]
Behind an editor flag (#180), `math.Pow(x, 1)` and `math.Pow(x, 2)`, sure. But not without it, I think.

In https://github.com/dominikh/go-staticcheck/issues/63#issuecomment-267096912, I said:

> > Nobody (heh, right…) will argue that `math.Pow(x, 2)` is simpler or clearer than `x*x`.
>
> Context matters, and I expect in some (rare) cases, the context will dictate which of the two styles is more appropriate. I don't think you can make a blanket statement that applies in all cases.
>
> Same goes for `errors.New` vs `fmt.Errorf`, `fmt.Println` vs `fmt.Printf`, etc.

Here's an example of what I meant. I wouldn't want to have to rewrite code like this because `gosimple` says `x*x` is simpler than `math.Pow(x, 2)`:

```Go
func someMathThingy(x float64) float64 {
	return 0 +
		math.Pow(x, 1) +
		math.Pow(x, 1*2) +
		math.Pow(x, 1*2*3) +
		math.Pow(x, 1*2*3*4) +
		math.Pow(x, 1*2*3*4*5)
}
```

In this context, `math.Pow(x, 2)` is not worse than `x*x`.

**Comment by dominikh** [comment]
Right. At this point, I would only consider it in the context of #180, as an editor quickfix.
