### ISSUE TITLE
staticcheck: check for accidental shadowing in else branch

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#217]
```
package main

import "fmt"

func main() {
	x := interface{}(1)
	if x, ok := x.(complex128); ok {
	} else {
		fmt.Println(x)
	}
}
```

The above code shadows `x` in the `else` branch, and its value is the zero value of the failed type assertion. This is usually a bug.

Let's run a test on our Go corpus to determine if flagging this causes false positives in real code.

**Comment by shurcooL** [comment]
You should be mindful of this being possible:

```Go
package main

import "fmt"

func main() {
	x := interface{}(1)
	if y, ok := x.(complex128); !ok {
	} else {
		fmt.Println(y)
	}
}
```

Note that due to the if condition being `!ok` in this snippet, the `else` branch is executed when the type assertion is successful, so `x` can have any value (not guaranteed to be zero).

Also, would you consider this as something worth flagging?

```Go
package main

import "fmt"

func main() {
	x := interface{}(1)
	if y, ok := x.(complex128); ok {
	} else {
		fmt.Println(y)
	}
}
```

The `y` no longer shadows `x`, but it's only being used when `ok` is false, i.e., type assertion fails, hence its value is guaranteed to be zero.

Perhaps these cases can be generalized further.

**Comment by dominikh** [comment]
Your first example wouldn't trigger the check. It is looking for `ok`, not `!ok`. Your second example may have merit, but is out of scope for this check. It might make sense in the "variable has always its zero value" line of checks.
