### ISSUE TITLE
staticcheck: catch useless if in a switch

### ISSUE THREAD

**Issue by xyproto** [dominikh/go-tools#223]
Consider this function that uses an `if` within a `switch`:

```go
func cmp(a, b int) bool {
  switch a {
    case C_RSP:
      if b == C_REG {
        return true
      }
  }
  return false
}
```

Assembly output with gccgo 7.2:

```asm
main.cmp:
  cmp rsp, QWORD PTR %fs:112
  jnb .L7
  mov r10d, 8
  mov r11d, 0
  call __morestack
  ret
.L7:
  push rbp
  mov rbp, rsp
  mov QWORD PTR [rbp-24], rdi
  mov QWORD PTR [rbp-32], rsi
  mov BYTE PTR [rbp-1], 0
  mov rax, QWORD PTR [rbp-24]
  cmp rax, 1
  jne .L2
  cmp QWORD PTR [rbp-32], 2
  jne .L6
  mov BYTE PTR [rbp-1], 1
  movzx eax, BYTE PTR [rbp-1]
  jmp .L5
.L6:
  nop
.L2:
  mov BYTE PTR [rbp-1], 0
  movzx eax, BYTE PTR [rbp-1]
.L5:
  pop rbp
  ret
```

Function that returns directly from within the case, dropping the `if`:

```go
func cmp(a, b int) bool {
  switch a {
    case C_RSP:
      return b == C_REG
  }
  return false
}
```

Assembly output with gccgo 7.2:

```asm
main.cmp:
  cmp rsp, QWORD PTR %fs:112
  jnb .L6
  mov r10d, 8
  mov r11d, 0
  call __morestack
  ret
.L6:
  push rbp
  mov rbp, rsp
  mov QWORD PTR [rbp-24], rdi
  mov QWORD PTR [rbp-32], rsi
  mov BYTE PTR [rbp-1], 0
  mov rax, QWORD PTR [rbp-24]
  cmp rax, 1
  jne .L5
  cmp QWORD PTR [rbp-32], 2
  sete al
  mov BYTE PTR [rbp-1], al
  movzx eax, BYTE PTR [rbp-1]
  jmp .L4
.L5:
  mov BYTE PTR [rbp-1], 0
  movzx eax, BYTE PTR [rbp-1]
.L4:
  pop rbp
  ret
```

Full go code that I used for testing at https://go.godbolt.org:

```go
package main

const C_RSP = 1
const C_REG = 2

func cmp(a, b int) bool {
  switch a {
    case C_RSP:
      return b == C_REG
  }
  return false
}

func main() {
  a := C_RSP
  b := C_REG
  cmp(a, b)
}
```

If the staticcheck tool would catch useless if checks within switches followed by `return true` or `return false`, some code might be improved.

**Comment by dominikh** [comment]
I don't think that's something I want to flag. Not only depends it on just the right constellation of code (only this particular scenario is functionally equivalent before and after the transformation), it also doesn't apply to most users who don't care about a few nanoseconds, possibly in code that isn't even on a hot path.

If anything this should be a compiler optimization, and I'm quite certain that this case is in fact optimized by compilers. It's a bit hard to test with gccgo because I don't know the right magic to prevent inlining, but after inlining, it's optimized to trivial code. I expect the same to happen in the non-inlined case. Do note that gcc doesn't apply optimizations by default (except for a few very basic ones) and you will have to specify one of the -O options.
