### ISSUE TITLE
unused with -export flag does not know String() and Error() are used

### ISSUE THREAD

**Issue by dzbarsky** [dominikh/go-tools#234]
These satisfy standard lib interfaces and deleting them is probably not what you want. Can they be whitelisted instead?

**Comment by dominikh** [comment]
`unused` considers all known interfaces and treats methods that fit those interfaces as used. The set of known interfaces depends on the set of transitively imported packages. That is, if any of the packages you specified on the command line transitively import `fmt`, then `fmt.Stringer` will be considered and no `String() string` method will be marked as unused.

To demonstrate with a trivial example:

```
package pkg
var _ T
type T struct{}
func (T) String() string { return "" }
```

Running `unused -exported pkg` results in `foo.go:4:10: func T.String is unused (U1000)`, because with this set of packages, there is no way that `T` will ever end up being used as an `fmt.Stringer`. Running `unused -exported pkg net/http`, however, does not complain about `T.String`, because `net/http` either directly or indirectly imports `fmt`, which means `T.String` might be used.

If you've run into this issue, you may be using the `-exported` flag incorrectly. The list of packages you specify when using `-exported` defines your whole "universe" of Go code. It is assumed that no other packages exist that use your code. It is intended for entire applications that do not expose APIs for public consumption (things like Docker, excluding their API clients).

If you have a use case that `unused` doesn't cover, please go into more detail, by showing real code, real command line invocations and explaining to me the desired output.

**Comment by dzbarsky** [comment]
Yes, I understand this, I am running `unused` over all code in my project (not including vendored dependencies but that doesn't matter).

Here's an example:
`path/to/interface.go:464:17: func NSPath.String is unused (U1000)`

relevant code: 

```func (p NSPath) String() {
	fmt.Sprintf("%s[%q]", p.NSID, p.Path)
}```

how can `unused` tell that this object is not passed as `interface{}` to something which then uses it as `fmt.Stringer`?

**Comment by dominikh** [comment]
That function is `String()`, not `String() string`, it returns no value. It doesn't match the fmt.Stringer interface and is in general absolutely useless, as the result of fmt.Sprintf is simply discarded.

**Comment by dzbarsky** [comment]
Oh, that code is silly. Thanks, I agree this issue is invalid

**Comment by dominikh** [comment]
@dzbarsky I recommend you also use `staticcheck`, which would've caught this bug :-)
