### ISSUE TITLE
Consider renaming docs for checks to add .markdown extension

### ISSUE THREAD

**Issue by AlekSi** [dominikh/go-tools#245]
If files like https://github.com/dominikh/go-tools/blob/master/cmd/staticcheck/docs/checks/SA6002 will have `.markdown` extension, they will be rendered properly on GitHub.

**Comment by dominikh** [comment]
These files are an internal artifact, used by scripts to generate https://staticcheck.io/docs/ – and we don't want GitHub to render them as actual markdown documents. We'd also not want to make any adjustments to the files to make them render prettier (for example by prefixing the first line with `# `) – These files are restricted to a specific subset of markdown that makes them easy to feed into my scripts.

Eventually, these files may even go away, when we turn them into Go code so that tools can more easily consume them.

**Comment by AlekSi** [comment]
I see, thank you. JFYI: that file is the first Google hit for `SA6002`, that's why I proposed that.

**Comment by dominikh** [comment]
I shall look into improving the google results for searches like that!
