### ISSUE TITLE
`_ := method` should not report "no new variables on left side of :="

### ISSUE THREAD

**Issue by ryan-ju** [dominikh/go-tools#259]
`_` is a wildcard placeholder that means "I know this function returns something but I want to ignore it".  

This is useful when you want to ignore an error, but don't want to hide the fact that you're ignoring it.

```
// This is safer 
_ := functionReturnsError()

// This is not safe.  If something goes wrong, you don't know if you forgot to catch an error somewhere.
functionReturnsError()
```

This linter reports `_ := functionReturnsError()` as `no new variables on left side of :=
`.

**Comment by luna-duclos** [comment]
Just removing the `:` in that statement should fix this, no ?

**Comment by ryan-ju** [comment]
Thanks for the tip, removing `:` worked.

**Comment by shurcooL** [comment]
For posterity, "no new variables on left side of :=" is an error coming from the Go compiler, not a message from this linter.

See https://play.golang.org/p/uJXptJ60NUE.

The linter prints compilation errors when they occur, and you need to fix those first, because it can only run on Go code that compiles successfully.
