### ISSUE TITLE
simple: reports the same mistake twice

### ISSUE THREAD

**Issue by opennota** [dominikh/go-tools#273]
gosimple prints two identical lines 
```
a.go:28:3: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013)
a.go:28:3: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013)
```

when asked to check the following file

``` Go
package a

import "github.com/boltdb/bolt"

type DB struct {
	*bolt.DB
}

func OpenDatabase(path string, options *bolt.Options) (DB, error) {
	db, err := bolt.Open(path, 0600, options)
	if err != nil {
		return DB{}, err
	}
	if err := db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte("index"))
		if err != nil {
			return err
		}
		_, err = tx.CreateBucketIfNotExists([]byte("fragments"))
		if err != nil {
			return err
		}
		_, err = tx.CreateBucketIfNotExists([]byte("versions"))
		if err != nil {
			return err
		}
		_, err = tx.CreateBucketIfNotExists([]byte("scratchpad"))
		if err != nil {
			return err
		}
		return nil
	}); err != nil {
		return DB{}, err
	}
	return DB{db}, nil
}
```

**Comment by dominikh** [comment]
Ironic. Ideally, it would match zero times, yet it matches twice... /cc @shurcooL

**Comment by shurcooL** [comment]
> Ideally, it would match zero times

Why do you say that? I think printing the message once would be the expected behavior.

Was there a specific reason you /cc'ed me, or was it just for my information?

**Comment by dominikh** [comment]
@shurcooL I cc'ed you for your information, because I previously expressed my dislike for the check to you. The reason I believe that gosimple shouldn't flag that line is because it is consistent with all the previous `if err != nil` lines.

I believe it was you who once similarly argued that it shouldn't be flagged to make future changes to the code easier.

**Comment by shurcooL** [comment]
> I believe it was you who once similarly argued that it shouldn't be flagged to make future changes to the code easier.

Yes, I would estimate it at around 2016 and prior that I argued that. But since then, I've realized the mistake in my logic, and readjusted my world-view to take the mistake into account. I've been very happy with the new world-view I've undertaken after discovering the mistake in my original thinking. Allow me to explain, and apologies for not finding a way to express my thoughts more succinctly.

From https://staticcheck.io/docs/gosimple#overview, `gosimple` is described as:

> Gosimple makes suggestions that simplify your code. Unlike staticcheck, its purpose is not to find incorrect code constructs. Instead, it tries to make your code simpler, by pointing out unnecessarily complex constructs.
>
> Its main audience is programmers who are new to Go, not yet aware of all of its features and the extent of its standard library. All of its suggestions should make you go oh! that's simpler!.
>
> Even more experienced programmers can get value out of gosimple, as it will recommend new features in the language that you might have missed in the release notes.
>
> Gosimple is best experienced locally, either directly in your editor, or for example as a pre-commit hook. It is possible to run gosimple in CI, but you may not want to fail entire builds because of it.

I think it's important to realize that the concept of simple code is often fundamentally at odds with consistent code in a specific context, or code that is easier to modify in certain ways.

Consider the following examples. Take S1000, which suggests that:

```Go
select {
case x := <-ch:
	fmt.Println(x)
}
```

Can be written more simply as:

```Go
x := <-ch
fmt.Println(x)
```

I think you would agree the latter is indeed simpler code. However, If the code preceding the `select` statement was other `select` statements with multiple cases, then applying the simplification would make the code not consistent with all the previous `select` statements.

Also, if the goal becomes to modify the code to add more cases, then the original code is easier (fewer keypresses) to modify than the simplified code.

The same pattern can be observed with most `gosimple` checks:

-	S1001 makes code simpler, but potentially less consistent if the original code in context was surrounded with other `for range` loops that could not be replaced with `copy`.

-	S1005 makes code simpler, but potentially less consistent if the original code in context was surrounded with other statements where the identifier was not blank.

-	S1012 makes code simpler, but potentially less consistent if the original code in context was surrounded with other statements that used `Sub` method (but not using `time.Now()` as the initial time).

-	Etc., etc.

In the end, the purpose and scope of the `gosimple` tool is to help spot opportunities to write simpler code, and I think the S1013 check fits that criteria well. I think there's no argument that the following single line of code:

```Go
return err
```

Is *simpler* than the following four lines:

```Go
if err != nil {
	return err
}
return nil
```

However, whether or not to apply the S1013 simplification suggestions depends on the situation. If you're in the middle of writing a prototype and are rapidly changing it so that the final `return err` is often changing, then not applying S1013 is completely reasonable. But if your goal is to clean up and write the simplest possible code before committing, I think it's a valid and helpful suggestion.

I find that most of the final `return err` lines I write change very infrequently, and when they do, I find it very easy to replace the `return err` with `if err != nil { return err }` in my editor. It does not deter me from wanting to apply S1013 in my final code whenever it comes up.

**Comment by dominikh** [comment]
> I think it's important to realize that the concept of simple code is often fundamentally at odds with consistent code in a specific context

I don't believe this to be true, given the correct definition of simple. By simple we do not mean "strictly shorter". We mean easier to follow and understand. Code, after it has been run through gosimple, should be easier to read. Sometimes, consistency is relevant to being easy to understand, sometime it is not.

> I think you would agree the latter is indeed simpler code. However, If the code preceding the select statement was other select statements with multiple cases, then applying the simplification would make the code not consistent with all the previous select statements

I do not think so. Selecting from channels, and receiving from a single channel, are distinctly different operations. There is no consistency to begin with, and the simplified version is simpler because it makes it immediately obvious which operation is being executed.

> Also, if the goal becomes to modify the code to add more cases, then the original code is easier (fewer keypresses) to modify than the simplified code.

> S1001 makes code simpler, but potentially less consistent if the original code in context was surrounded with other for range loops that could not be replaced with copy.

Possibly so. With some mental gymnastics one could argue that they're different operations. With less mental exercise, one could argue that simplicity trumps consistency in this case.

> S1012 makes code simpler, but potentially less consistent if the original code in context was surrounded with other statements that used Sub method (but not using time.Now() as the initial time).

That is true, and we probably should take that into consideration and not make the suggestion in those cases.

> I think there's no argument that the following single line of code [...] Is simpler than the following four lines

There is actually an argument to be had here. It is _shorter_, for sure. It is also simpler _without context_. In context, however, it seems less simple because it looks different from the surrounding code, while doing the exact same thing. It is therefore more difficult to read and follow, IMO.
