### ISSUE TITLE
unused: unused exported functions in package main are marked used

### ISSUE THREAD

**Issue by xxjapp** [dominikh/go-tools#284]
func (abc *Abc)Func1() not reported as unused

    package main

    import (
    	"fmt"
    )

    // Abc Abc
    type Abc struct {
    }

    // Func1 Func1 not reported as unused!!
    func (abc *Abc)Func1() {
    }

    func main() {
    	var abc *Abc
    	fmt.Println("Hello, playground", abc)
    }

**Comment by shurcooL** [comment]
To be more precise, it’s a method. Its existence makes the `Abc` type implement the following interface:

```Go
type Func1er interface {
	Func1()
}
```

If this were a library rather than command, you wouldn’t be able to tell whether implementing such an interface is being used by some other package or not.

It may also be used via reflection.

However, given this is a command and reflection isn’t used, in theory, it should be possible to detect it as unused. But it might be hard and the edge cases might be tricky.

Those are my initial thoughts, @dominikh should be able to comment more.

**Comment by dominikh** [comment]
The issue is that _unused_ doesn't differentiate between main and non-main packages when it comes to methods.
