### ISSUE TITLE
staticcheck:(SA2000) the checker of checking Waitgroup Add race has a FN

### ISSUE THREAD

**Issue by Tengfei1010** [dominikh/go-tools#360]
``` go
func fn1() {
	wg := sync.WaitGroup{}
	go func() {
		log("debug......")
		wg.Add(1)
                ......
		wg.Done()
	}()
	wg.Wait()
}
```
There is a data-race example that staticcheck could not combat it.
If there are some code before "wg.add()", the checker will ignore this case.

**Comment by dominikh** [comment]
We're specifically looking for `go func() { wg.Add(1)` to avoid false positives. Calling wg.Add in a goroutine isn't necessarily wrong; the goroutine may itself spawn more goroutines. That's why we're looking for a specific pattern that is commonly used incorrectly, and doesn't tend to lead to false positives. This necessarily leads to false negatives.

Since there are no (feasible) sound approaches to this, we have to rely on the aforementioned pattern matching and catch what we can without introducing false positives. As such, this falls under "Unfortunate".

**Comment by Tengfei1010** [comment]
@dominikh thanks!
