### ISSUE TITLE
Unused, const groups and completeness

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#365]
The standard library has a fair number of constants that are never used but exist for the sake of completeness (and possibly future use), usually in the context of protocol specifications. debug/dwarf, for example, has dozens of unused constants.

Currently, unused flags these constants as unused, which feels wrong. These constants don't hurt anyone; and having them readily available makes future additions to the code easier.

The only problem is detecting which constants can be ignored. The simplest approach would be to treat all constants in a single block as one unit, i.e. for

```
const (
  a = 1
  b = 2
  c = 3

  d = 4
  e = 5
  f = 6
)
```

at least one of `abc` and at least one of `def` would have to be used.

Would this approach lead to too many false negatives?

**Comment by ainar-g** [comment]
If this task is about exported constants only, then I think that my [proposal](https://github.com/dominikh/go-tools/issues/381#issuecomment-452847161) about U1001 would work well here. `unused` Would not report them by default, and if one does need to check exported identifiers, they can use per-line ignore annotations, which will also alert them when an annotation is outdated because the constant is now used.

If this task is about unexported constants as well, then _I guess_ the one block solution is _fine,_ but I would like to have a way to disable this behaviour. Writing every constant on its own line?

**Comment by dominikh** [comment]
Closed in 95e22af
