### ISSUE TITLE
stylecheck: consider requiring line comments to start with a space

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#407]
That is:
```
bad:
//Hello comment.
good:
// Hello comment.
```

Motivation:

* It (arguably) looks better.
* It's how almost everybody does it.
* The no-space variant may be considered by some tools to be an annotation, like `//lint:ignore`.

**Comment by dominikh** [comment]
How do we distinguish malformatted comments from tool directives? Not every tool adheres to the `tool:command` format.

**Comment by dominikh** [comment]
I am not comfortable with this. The heuristics are too brittle and will inevitably flag directives. Especially in the case of exported identifiers, it would lead to confusing warnings; we do not enforce that exported symbols have documentation, so why should the presence of said documentation be a criterion for this check. Finally, maintaining a list of well-known-directives isn't how I want to spend my time.

In the end, I don't believe that this is worth adding as a check. How to write comments should probably be the first thing you learn in school.

**Comment by dmitshur** [comment]
I have a style suggestion entry for this [here](https://dmitri.shuralyov.com/idiomatic-go#comments-for-humans-always-have-a-single-space-after-the-slashes). One relevant part from there is that:

> Temporarily commented out code should also have no spaces, but it's not meant to be committed.

That's a reason implementing a check would be more challenging, since it couldn't tell apart comments for humans vs temporarily commented out code.
