### ISSUE TITLE
Block-based ignore

### ISSUE THREAD

**Issue by narqo** [dominikh/go-tools#450]
As for 2019.1 staticcheck provides two macros to ignore certain checks: line-based and file-based, i.e. `//lint:ignore` and `//lint:file-ignore` respectively.

I propose to either extend the semantics of line-based to be a block-based or introduce a new one. 

The ignore rule must cover the following cases

```go
//lint:ignore U1000 the following variables are used in external code (generated or cgo)
var (
  errFoo = errors.New(···)
  errBar = errors.New(···)
)
```

```go
//lint:ignore U1000 the following constants are used in external code (generated or cgo)
const (
  enumStart int = iota
  foo
  bar
  enumEnd
)
```

**Comment by dominikh** [comment]
I'd rather avoid the warnings than introduce more facilities for ignoring them. Having to ignore issues should be a rare occurrence; having to ignore entire blocks of code sounds undesirable.

In this specific case (U1000 + "external" code) I'll need more information. What exactly do you mean by external code? Assembly and C? Because generated Go code, and cgo (which turns into Go code) should both be visible to the analysis, and correctly mark the variables as used.

For the enum case, there is also https://github.com/dominikh/go-tools/issues/365 (which has been implemented in the `incr` branch)

**Comment by narqo** [comment]
I wasn't sure if Go code, that is used in C can be analysed. Will it also work for a code linked via `//go:linkname` directive?

By generated code I ment a case similar to #338, but when one runs `staticcheck` without running code generation (stringer). E.g. when generated code isn't commited to the repo while linters (including staticcheck) are run as a parallel step on a CI.

If anyone should do that is a debatable topic, so I think we ca ignore it. #338 and #365 describe the real use cases, and this issue can be closed.

**Comment by dominikh** [comment]
> E.g. when generated code isn't commited to the repo while linters (including staticcheck) are run as a parallel step on a CI.

Yeah, don't do that. You want to test and analyse the actual code, not an incomplete version of the code. Always check in generated code (or, if for some reason you refuse to, generate it _before_ running tests and analyses).

> I wasn't sure if Go code, that is used in C can be analysed

C can only access those Go symbols that have the `//export` comment, which we support. We also support the `//go:linkname` directive.
