### ISSUE TITLE
Should I be able to install with modules?

### ISSUE THREAD

**Issue by cep21** [dominikh/go-tools#494]
I was unable to install incr branch of staticcheck with go modules default tool installation method.  It would be convenient if this worked.  What are your thoughts?

```
< GO111MODULE=on go get -u github.com/dominikh/go-tools/cmd/staticcheck@incr
go: finding github.com/dominikh/go-tools/cmd/staticcheck incr
go: finding github.com/dominikh/go-tools/cmd incr
go: finding github.com/dominikh/go-tools incr
go: finding honnef.co/go/tools/staticcheck latest
go: finding honnef.co/go/tools/lint/lintutil latest
go: finding honnef.co/go/tools/stylecheck latest
go: finding honnef.co/go/tools/simple latest
go: finding honnef.co/go/tools/lint latest
go: finding honnef.co/go/tools/unused latest
go: finding honnef.co/go/tools latest
go: finding golang.org/x/tools/go/analysis latest
go: finding golang.org/x/tools/go latest
go: finding golang.org/x/tools latest
# github.com/dominikh/go-tools/cmd/staticcheck
go/pkg/mod/github.com/dominikh/go-tools@v0.0.0-20190520034952-d4838094cf6d/cmd/staticcheck/staticcheck.go:24:20: undefined: simple.Analyzers
go/pkg/mod/github.com/dominikh/go-tools@v0.0.0-20190520034952-d4838094cf6d/cmd/staticcheck/staticcheck.go:27:20: undefined: staticcheck.Analyzers
go/pkg/mod/github.com/dominikh/go-tools@v0.0.0-20190520034952-d4838094cf6d/cmd/staticcheck/staticcheck.go:30:20: undefined: stylecheck.Analyzers
go/pkg/mod/github.com/dominikh/go-tools@v0.0.0-20190520034952-d4838094cf6d/cmd/staticcheck/staticcheck.go:34:7: undefined: unused.NewChecker
go/pkg/mod/github.com/dominikh/go-tools@v0.0.0-20190520034952-d4838094cf6d/cmd/staticcheck/staticcheck.go:42:12: undefined: lint.CumulativeChecker
go/pkg/mod/github.com/dominikh/go-tools@v0.0.0-20190520034952-d4838094cf6d/cmd/staticcheck/staticcheck.go:43:25: too many arguments in call to lintutil.ProcessFlagSet
```

**Comment by dominikh** [comment]
Please try `honnef.co/go/tools/cmd/staticcheck@incr` instead of the github.com URL.

**Comment by cep21** [comment]
That worked.  Is there a way to inspect the source code it is installing?  (the link redirects me to github).  Do you know why the github version doesn't work?

**Comment by dominikh** [comment]
> Do you know why the github version doesn't work?

`honnef.co/...` is the canonical import path, and the code in this repository imports packages using that import path. When you try to go get from `github.com/...`, you will download the module twice: once from github.com, at the specified `incr` version, and a second time from honnef.co due to the import, this time at the automatic `latest` version, which defaults to master, which isn't the code that is expected.

Traditional, non-module `go get` would throw an error when trying to get from `github.com` as cmd/staticcheck/staticcheck.go specifies the canonical import path `package main // import "honnef.co/go/tools/cmd/staticcheck"` – Module mode doesn't seem to do that, instead relying fully on `go.mod`. But since staticcheck doesn't currently have a go.mod file (#346), Go synthesizes one based on your command line, leading to this weird situation. I'm considering filing a bug with Go for this.

>  Is there a way to inspect the source code it is installing

Go in module mode downloads modules to the module cache, which is at $GOPATH/pkg/mod.

**Comment by cep21** [comment]
Thanks for the explanation!
