### ISSUE TITLE
simple: only suggests merging contiguous assignments

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#50]
This is suggested:

```
var i int
i = 3
```

But this isn't:

```
var i int
i2 := 4
i = 3
```

Reading your code, this seems to be on purpose. Why?

I can understand that "jumping" other statements makes the check more complex, as it's not certain that the code would still compile correctly. But it should be fine as long as all the statements you have to "jump" don't contain any reference to the declared variable.

**Comment by dominikh** [comment]
Extending the check doesn't have a good reward to cost ratio. The original check is a trivial AST-based check and is always strictly better (simpler). Extending the check would require observing uses of the variable between declaration and assignment, and it would have to try and deduce the user's original intention. On top of that, the extended form would have far fewer matches, making it not really worth it.

**Comment by mvdan** [comment]
Care to point out an example of when these new suggestions wouldn't be strictly better?

> On top of that, the extended form would have far fewer matches, making it not really worth it.

Unfortunately, I'm reading some code that reminds me of old C versions, where declarations had to be at the beginning of each block :(

**Comment by dominikh** [comment]
I don't have concrete examples, but the extended form would have more potential for subtle edge cases. Consider this:

```
var i int
i2 := 4
i = i2 + 1
```

You'd probably expect me to flag that, but the suggestion to simply merge the first and third line wouldn't be correct anymore, as the position of the assignment matters. Similarly, if we didn't limit the number of instructions between the declaration and assignment, the potential for rare but valid code patterns increases.

The current check is always right (sans nonsensical, self-referential initialization where one can easily substitute the zero value) because it's trivial. The extended check would be subtle, with little payoff.

**Comment by mvdan** [comment]
> You'd probably expect me to flag that, but the suggestion to simply merge the first and third line wouldn't be correct anymore, as the position of the assignment matters.

It will be alright as long as you merge into the latter, not the former. This is what I was thinking and what I usually do.

I understand if you find this work not worth it and want to close the issue unless someone else wishes to work on it. But I don't understand how this change could break the "always right" rule.

**Comment by dominikh** [comment]
> unless someone else wishes to work on it

I don't want to maintain it, either :)

> But I don't understand how this change could break the "always right" rule

Because of bugs, simple as that. My first mental implementation of your extended check didn't even consider the edge case from my earlier example, and I'm sure there are plenty more to go wrong on. It's also simply not an objective improvement anymore. `var x int; x = 1` has no benefit over `var x int = 1`. Having 20 lines of statements between the two, maybe there's a subjective reason for having declaration and initialization split up. For example, a lot of my code declares an `out` parameter at the top, when returning a slice or map of things that is gradually built. I'm sure there's some edge cases where it could be merged with the first assignment halfway across the function. It wouldn't be an improvement, and it would be hard to detect as something not worth flagging.

Gosimple tries to stick to objective suggestions. If you can argue over a suggestion, it's probably not a suggestion we should be making.

**Comment by mvdan** [comment]
Fair enough, thanks for considering!
