### ISSUE TITLE
Deprecation of struct should deprecate receiver functions

### ISSUE THREAD

**Issue by dchang-dchang** [dominikh/go-tools#508]
Proposal: Deprecating the struct should also mean that all of the structs receiver functions should also be deprecated

Basically, I've got a struct that I want to deprecate and it's got lots of receiver functions and I'd like to deprecate the receiver methods without having to hunt down all the methods (and possible forget one or two) and comment them with deprecation markers.

I've been thinking about this for a bit and I can't think of any examples where I wouldn't want this - as deprecating the struct means that I plan on removing that struct and thus all it's receiver functions as well.

Here's a simple test:

main.go
```go
package main

import (
	"fmt"

	"....../point"
)

func main() {
	p := point.New()
	fmt.Println(p.IsOrigin())
}
```

point/point.go
```go
package point

// Deprecated: do not use
type Point struct {
	X int
	Y int
}

func (p *Point) IsOrigin() bool {
	return p.X == 0 && p.Y == 0
}

// ... Potentially, many many more methods

func New() Point {
	return Point{X: 1, Y: 1}
}
```

Staticcheck outputs no errors, because I'm not directly creating the struct nor is the receiver marked as deprecated:
```
> staticcheck main.go
>
```

Admittedly, there's a bit of handwaving here:

How did you get the point? Well there's some function that gave it to you, and that should probably be deprecated as well...

Why don't you just mark the receiver function as deprecated? Well there's a lot of them and I'm lazy and don't want to have to put it everywhere

Would love to hear your thoughts and insights on this.

P.S. Thanks for all your work on static check! It's been a really great tool that helps us keep code quality high! Really appreciate it!

**Comment by dominikh** [comment]
I agree that you shouldn't have to deprecate each individual method, but I am not sure that automatically deprecating all methods of a deprecated type is the correct approach. I see a problem with doing this, as well as an alternative that should work in the majority of cases.

The problem is that as a consumer of other APIs, you may not be in control of the types you work with. Your `point.New` example might be the only API possible to use right now. Or the deprecated type might be a field in another struct, and you may have no choice but to use it. Not using deprecated types should be the responsibility of whoever instantiates the type, not whoever ends up with them.

This leads to my suggested solution: deprecate all "constructors" that users shouldn't use anymore. That is, deprecate `points.New`. Ideally there are only a handful of constructors. You handwaved this solution away, but didn't give any reason for why this isn't viable. Is doing this not viable for you?

> P.S. Thanks for all your work on static check! It's been a really great tool that helps us keep code quality high! Really appreciate it!

:heart:

**Comment by dchang-dchang** [comment]
I've got a strange mix of generated and handwritten code where I'd like to use static check to make sure that the handwritten code doesn't use any deprecated structs from another package (while it's fine for generated code to do so). We shouldn't overfit to my case. Happy to describe it more if you're interested.

You're probably right about deprecating a struct requires you to deprecate the struct and then manually find it's public constructors (hopefully a small set). I'd expect that we'd also have to manually find any other public method that returns that struct (maybe not as small of a set?)

How would this interact with embedded structs? I just tried this quick example as another way that a struct might make it out (besides constructors and methods that return that struct) and it seems that this doesn't throw an error. I don't have a good theory on what correct behavior for deprecated embedded structs should be.

```go
package main

import (
        "fmt"

        ".../point"
)

func main() {
        d := point.Dot{}
        d.X = 0
        d.Y = 0
        fmt.Println(d.IsOrigin())
}
```

```go
package point

// Deprecated: do not use
type Point struct {
        X int
        Y int
}

type Dot struct {
        Point
        Color string
}

func (p *Point) IsOrigin() bool {
        return p.X == 0 && p.Y == 0
}

// ... Potentially, many many more methods

func New() Point {
        return Point{X: 1, Y: 1}
}
```

**Comment by dominikh** [comment]
I think that deprecating methods on deprecated types, or even deprecating constructors, is a red herring. The real problem seems to arise from intra-package deprecation. 

The check for use of deprecated APIs explicitly allows the use of deprecated things from the same package. After all, a new, not deprecated API can internally be built upon a deprecated API. That something is deprecated only affects other packages, 3rd party users. Even having (embedded) fields of deprecated types can be fine sometimes.

The problem you are facing, however, is leaking deprecated APIs. You have deprecated a type, and you want to ensure that no other type, even in the same package, exposes this type to users. Be it via constructors, fields, or embedding. Unfortunately I do not have a good solution to this. But I don't believe that this is something that can be retro-fitted into the existing check. They're really two separate checks. But I don't see a way of implementing a new check for this without either causing too many false positives (see above for valid reasons to use deprecated APIs within the same package), or inventing new conventions for "really deprecating" something.

**Comment by dchang-dchang** [comment]
Thanks! Appreciate the help!
