### ISSUE TITLE
Add back the "--ignore" command line flag

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#514]
Hi,
I just updated to the latest version of staticcheck, which doesn't recognize the `--ignore` flag. The process of tracking down the new workflow has been pretty frustrating; it's not clear where the new behavior is documented and at a first approximation it seems like the `--ignore` behavior was simply removed. 

At the very least it would be good if you could catch the `--ignore` flag and print an error that links to docs, or print out the new TOML that you need.

Updates golang/dep#2178.

**Comment by kevinburke** [comment]
If you are reading this, you now need to embed `//lint:ignore` directives above each line (or at the top of the file) for files you want to ignore. See https://staticcheck.io/docs/#ignoring-problems for more info.

Updates #515.

**Comment by dominikh** [comment]
The [2019.1 release notes](http://staticcheck.io/changes/2019.1) document that `-ignore` is going away, and point towards the replacement:

>  Finally, the -ignore flag has been replaced by [linter directives](http://staticcheck.io/docs/#ignoring-problems).

The 2019.2 release notes, which are currently being prepared for the 2019.2 release, state that `-ignore` has been removed. We can point to the alternative again, but the solution remains the same: reading the changelogs.

> I just updated to the latest version of staticcheck

Strictly speaking you updated to a development version of staticcheck, not the latest [released] version, which currently is 2019.1. Staticcheck has actual releases, to present users with a consistent experience, and to provide accompanying changelogs to document what exactly has changed.

Since the `-ignore` flag has been deprecated for a whole release, and for half a year, I am not likely to add it back.

**Comment by kevinburke** [comment]
So here are the steps I was supposed to follow I guess:

- click to the "Releases" page
- for the release I am looking for click through to the "full changelog" link
- scroll 2/3rds of the way down the page and click on "linter directives"
- Read

That's a pretty complex set of steps to follow!!

**Comment by dominikh** [comment]
@kevinburke The expected workflow looks more like this:

- Be using a released version of staticcheck
- Hear of a new release via one of our announcement channels
- Read the full changelog, which is referenced in the release note
- After being aware of the changes, update to the new release. Or hold off on updating if need be

That is. updates should be made consciously. Features may change, new checks may get added (which may suddenly start failing your CI if updating at random). Living on `master` is for people who want the bleeding edge.

**Comment by kevinburke** [comment]
Sure... in a CI environment the easiest way to install staticcheck - since you already have Go installed - is generally to run `go get honnef.co/path/to/staticcheck` ( http://honnef.co/path/to/staticcheck` )...

Kevin Burke
phone: 925-271-7005 | kevin.burke.dev ( https://kevin.burke.dev )

**Comment by dominikh** [comment]
> go get honnef.co/path/to/staticcheck

I recognize that. Getting people to use specific tags instead of just `go get`ing the master branch has been an ongoing issue.

Luckily, starting with the upcoming 2019.2 release, we will be using Go modules and tags that Go modules understand. For people who use Go modules this means that `go get` will get the latest release, not master. It'll also allow people to more easily record tool dependencies, encoding them in go.mod like any other dependency.
