### ISSUE TITLE
staticcheck is not finding all nested packages via path/...

### ISSUE THREAD

**Issue by ex-nerd** [dominikh/go-tools#524]
I'm working with a large monorepo with many microservices each stored in their own directory path, something like this:

```
root/
  shared/other-packages-here/
  services/
    service1/
      src/
        service1/service1.go
          s1_subpackage/file.go
    service2/
      src/
        service2/service2.go
          s2_subpackage/file.go
```

I'm trying to run staticcheck on all detected services, from inside of the `root` directory via `staticcheck services/...` but there is no output (and the exit code is `0`, showing no errors).  This works fine with other tools like `golint services/...` which properly traverse the tree finding and linting all packages.

The only way I've found to make this work script something like the following for each of my services, which of course means capturing/managing a number of different exit statuses, etc:

```bash
cd services/service1/
GOPATH="$GOPATH:/full/path/to/root/services/service1" staticcheck ./...
```

Attempting to run from a higher level directory results in a bunch of `go build service1/s1_subpackage: no Go files in` errors. These go away if I add each service to the GOPATH but there are a LOT of those and even then staticcheck just exits without an error or status message (as it does when just running `staticcheck ./...` from the root directory).

### Other stuff:

- staticcheck version: `staticcheck (no version)` (installed just now via `go get -u honnef.co/go/tools/cmd/...`)
- staticcheck -debug.version: `Compiled with Go version: go1.11.10`
- go version: go version go1.11.10 darwin/amd64
- go env: ```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/REDACTED/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/REDACTED/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b6/fgks4v995mdgf5qqcj4g0d0ncssyb4/T/go-build600629788=/tmp/go-build -gno-record-gcc-switches -fno-common"```
- Exactly which command you ran: `staticcheck mypath/...`
- Output of the command and what's wrong with the output
- Where we can read the code you're running staticcheck on: sorry, private corporate repo

**Comment by dominikh** [comment]
If each of your services constitutes its own, separate GOPATH, then it is not surprising that `...` isn't working. `go build mypath/...` would not work, either, in that scenario. Staticcheck expects the same kind of setup that `go` does. GOPATH has to be configured correctly, and `...` probably doesn't cross GOPATHs (though I haven't checked that.).

The reason that staticcheck exits successfully is that the pattern evaluates to zero packages, and we checked all zero of them successfully.

Golint probably works here because it's a rather simple linter, and is happy working on a file per file basis. It also uses an older model of loading packages which doesn't rely on the underlying build system as much.

This is pretty much working as intended, and down to a somewhat unusual repository layout.
