### ISSUE TITLE
errcheck: backport exclusion facilities

### ISSUE THREAD

**Issue by tamird** [dominikh/go-tools#57]
Particularly:

https://github.com/kisielk/errcheck/pull/115
https://github.com/kisielk/errcheck/pull/116

**Comment by dominikh** [comment]
By the time that I actually release errcheck-ng, it shouldn't need manual filter lists. Instead, it will deduce enough information about the code to automatically ignore impossible errors.

**Comment by tamird** [comment]
:+1: but we'll still want custom excludes.

**Comment by tamird** [comment]
While you're working on this, it would also be good to be able to specify additional "checked" types. For instance, [`*github.com/cockroachdb/cockroach/pkg/roachpb.Error`](https://godoc.org/github.com/cockroachdb/cockroach/pkg/roachpb#Error) is a structured error type that we want to always check.

**Comment by dominikh** [comment]
I no longer intend to work on my own errcheck. Writing a useful version of errcheck requires whole-program analysis and points-to analysis. It would be incredibly slow and memory intensive for real world applications. We can't possibly run it as part of staticcheck, and the Go community is not open to static analysis that needs hours or days to complete.

I will remove the existing errcheck from the repository. It is a minimal prototype and was never meant to be used in production. Since we're dropping support for errcheck, this issue is no longer relevant and will be closed.
