### ISSUE TITLE
staticcheck: warn when program uses rand without seed

### ISSUE THREAD

**Issue by bboreham** [dominikh/go-tools#622]
Example program: https://play.golang.org/p/RbLQ-MOqOm0

(this is from a real-world fail but I don't like to point at the location)

In Go 1.12 and 1.13 (at least), `rand.Intn(5000)` is 3081.  Every time.
The programmer should have done something like `rand.Seed(time.Now().UnixNano())` to make it come out different each time.

I see there would be false positives when library code doesn't want to impose a seeding policy. Or test code that really does want the same random numbers each time.

**Comment by dominikh** [comment]
I don't think we can flag this without causing annoying false positives, for the reasons you have mentioned, plus for the reason that any imported package may seed it for us as well. IOW, it's a whole-program analysis.

At best we might restrict the analysis to non-test code in package main, and also analyze every transitive dependency for whether it might seed the RNG. That's both very specific (unlikely to find many bugs due to the restrictions) and very expensive. I'm not sure it's worth implementing a check with those restrictions.

**Comment by dominikh** [comment]
As of Go 1.20, the global Source in math/rand gets seeded automatically, rendering this check unnecessary.
