### ISSUE TITLE
staticcheck: flag definitely pointless nil pointer check

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#626]
Seen in real code:

```
x := someExpression
if &x == nil { ... }
```

it is impossible for `&x` to be nil.

**Comment by ainar-g** [comment]
<blockquote>
it is impossible for <code>&x</code> to be nil.
</blockquote>

<p>
[source?] :-D
</p>

<p>
I'm only half-joking here.  <code>struct{}</code> has a size of zero
bytes, and most of the time all instances of <code>struct{}</code> have
the same address:
<a href="https://play.golang.org/p/gaOUsg-TLWi">https://play.golang.org/p/gaOUsg-TLWi</a>.
</p>

<p>
Technically, since the size of these values are zero, nothing prevents
a Go implementation from making their address always be
<code>0x00000000</code>.
</p>

<p>
I'm in no way against this check! I'm merely documenting a corner-case
where this assumption may be broken :-)
</p>

**Comment by dominikh** [comment]
They may have the same address, but they may not be null pointers. Nothing in the spec states that types of size zero are _so_ special that loads and stores of values of those types aren't permitted. And if loads and stores _are_ to be permitted, the address must be non-zero.

**Comment by dominikh** [comment]
I suppose a sufficiently weird runtime could omit all loads and stores to `*struct{}`, or represent actual nil pointers as something else than zero, and make sure reflection, cgo and everything else is aware of these weird pointers to ensure nothing ever tries to read at the physical address 0; however the odds of that are smaller than the address of &struct{}{}.

**Comment by dgryski** [comment]
I found more hits using this query:

Locally:
```
zoekt '"\&[a-zA-Z0-9]+ == nil"'
```

And: [cs.bazel.build](https://cs.bazel.build/search?q=f%3A%5C.go+"%5C%26%5Ba-zA-Z0-9%5D%2B+%3D%3D+nil")
