### ISSUE TITLE
staticcheck performance regression

### ISSUE THREAD

**Issue by alecthomas** [dominikh/go-tools#63]
gometalinter vendors all of its linters, and was previously using staticcheck @ 9e27cae723244b5535cbaf41a730a208dddc9715. Since updating to HEAD, staticcheck has gotten a *lot* slower. Here's a before and after on a fairly small codebase:

```
[aat@cavern:~/Projects/kingpin]time staticcheck .
staticcheck .  0.16s user 0.02s system 171% cpu 0.105 total
[aat@cavern:~/Projects/kingpin]time staticcheck .
staticcheck .  9.52s user 1.22s system 381% cpu 2.820 total
```

**Comment by dominikh** [comment]
9e27cae723244b5535cbaf41a730a208dddc9715 is an extremely old commit (4+ months old). The underlying architecture of the linters has changed, applying much more in-depth analysis, handling outdated dependencies and cgo correctly and doing inter-procedural analyses. This does come with a performance impact, which is in line with what you're seeing.

**Comment by alecthomas** [comment]
But still, 3 seconds to check 7K lines (including tests), even when all dependencies are compiled?

**Comment by dominikh** [comment]
All dependencies are imported from source code and analyzed for certain characteristics (deprecated objects, function purity, ...). We couldn't extract all information that we require from the compiled object files.

**Comment by stevenh** [comment]
While the improvement in accuracy is good, speed is also very important especially when using them for commit validation.

The extreme regression in performance means we're going to have to disable staticcheck totally, which is having the opposite effect than is intended by the improvements (no coverage vs not so accurate coverage).

Why? Well on our code base a full gometalinter pass used to take 14 seconds, now due to these changes it takes just under 5 minutes (longer that the full build and all tests); which is just unusably slow.

**Comment by mvdan** [comment]
@stevenh you can't have linters that are good and fast at the same time. If you want your linters to take a couple of seconds, use linters that are less powerful.

**Comment by bradleyfalzon** [comment]
Perhaps staticcheck et al can still be ran in CI though, just not on every commit?

**Comment by stevenh** [comment]
By every commit I was actually referring to CI as every commit runs through CI.

When you have even a small number of developers making the CI checks, before review, take 10 mins instead of 5 mins just for a little bit more accuracy is just not worth it as it holds up the entire dev process.

The checks done previously were useful and completed in seconds, yes the new checks picked up 1 or 2 little extra things, but we have to way the pros and cons and in this case the cons (slow speed) far out way the pros.

I've not looked at the changes, but would it possible to have a quick mode similar to the previous versions and a slow mode with all the new checks. That way we can get 90%+ coverage all he time and then use a slow pass to get better coverage when needed; similar to how go test splits normal and slow tests.

**Comment by dominikh** [comment]
> When you have even a small number of developers making the CI checks, before review, take 10 mins instead of 5 mins just for a little bit more accuracy is just not worth it as it holds up the entire dev process.

That sounds to me like the CI system isn't working efficiently. For large code bases, you probably don't want to test the entire code base on every commit. Instead, you want to test the affected code (i.e. the changed packages and their reverse dependencies.)

> The checks done previously were useful and completed in seconds, yes the new checks picked up 1 or 2 little extra things, but we have to way the pros and cons and in this case the cons (slow speed) far out way the pros

I disagree. For a start, "1 or 2 little extra things" is a false characterization of the improvements. While it may be true that the code you write is near perfect and doesn't benefit from the newer checks, they're not "little" in any way, and aim to detect issues that a simple compile+test cycle wouldn't detect. The checks that ran incredibly fast really weren't that useful in CI to begin with.

> I've not looked at the changes, but would it possible to have a quick mode similar to the previous versions and a slow mode with all the new checks. That way we can get 90%+ coverage all he time and then use a slow pass to get better coverage when needed; similar to how go test splits normal and slow tests.

That would require two disjoint code bases. There isn't a set of checks that are slow. The slowness comes from the underlying type checking and analysis system, not individual checks. You are, however, free to vendor an old version of staticcheck and use that instead.

**Comment by dominikh** [comment]
For the record, we're constantly trying to improve the performance of the tools, where possible. We also greatly appreciate contributions to that effect. 

To be clear, however, they will never reach their old speeds. Those were due to a flawed architecture that didn't even check all packages correctly (skipping over those with missing gc archives for dependencies). The new architecture is much closer to realistic speeds, roughly matching tools like errcheck. That doesn't mean that we can't further optimize it to shave off some seconds here or there, though.

**Comment by stevenh** [comment]
Thanks @dominikh for the feedback, I appreciate the reasoning behind your changes.

We already had had a number of the standard linters disabled errcheck being one for exactly this reason, its too slow.

Thinking a little out side the box, would it be possible to merge staticcheck, gosimple and errcheck eliminating the multiple parse passes and hence significantly reducing the time taken when running all three test sets?

Combine that with the option to the binary to process each of the current linters test, it will still provider the same functionality but at significantly reduced cost, time wise.

**Comment by dominikh** [comment]
> Thinking a little out side the box, would it be possible to merge staticcheck, gosimple and errcheck eliminating the multiple parse passes and hence significantly reducing the time taken when running all three test sets?

I am planning to provide a tool that can run staticcheck, gosimple and unused at once (with an option to run a subset of these). One stat I've heard before was that it'd result in a 70% runtime reduction.

I am also working on my own version of errcheck, which, once it's been released, would also be part of that tool. I won,t however, integrate the original errcheck in the tool, as it would require some changes to it.

For tools that aren't mine, you might be interested in https://github.com/mvdan/lint

**Comment by myitcv** [comment]
Also significant (not measured so I don't know to what extent) is not re-running these tools on packages (or its dependencies) that haven't changed. Following a strategy similar to [`gt`](https://godoc.org/rsc.io/gt) is a sensible way forward in addition to the changes described by @dominikh
