### ISSUE TITLE
Staticcheck seems to be running but produces no output

### ISSUE THREAD

**Issue by bshetty** [dominikh/go-tools#662]
When i start staticcheck it runs for a while but produces no output
Please make sure to include the following information in your issue report:

- The output of 'staticcheck -version'
```
staticcheck 2019.2.2
```
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck 2019.2.2

Compiled with Go version: go1.13.4
Main module:
        honnef.co/go/tools
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
```

- The output of 'go version'
```
go version go1.13.4 linux/amd64
```

- The output of 'go env'
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/go/src/honnef.co/go/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build753631820=/tmp/go-build -gno-record-gcc-switches"
```
- Exactly which command you ran
```
staticcheck -checks=[all] staticcheck.go
staticcheck ...
staticcheck honnef.co/go/tools/staticcheck/...
staticcheck -checks=[all] honnef.co/go/tools/staticcheck/...
```

- Output of the command and what's wrong with the output
no output generated
- Where we can read the code you're running staticcheck on
  (GitHub repo, link to playground, code embedded in the issue, ...)
honnef.co/go/tools/cmd/staticcheck

**Comment by dominikh** [comment]
Staticcheck reports problems it finds. If there are no problems, there is nothing to print.

- `-checks=[all]` is incorrect, you meant `-checks=all`. 
- `staticcheck honnef.co/go/tools/staticcheck/...` won't print anything because there are no errors in the honnef.co/go/tools/staticcheck package. 
- `staticcheck ...` – the interpretation of `...` depends on your current working directory and whether you're using modules or GOPATH. Assuming your working directory was somewhere in honnef.co/go/tools, `staticcheck ...` should produce some output, but it will likely take a while to do so, as it has to check a large amount of code, including all dependencies of staticcheck, as well as the Go standard library.

In general, I recommend you use staticcheck on your own code, and not on that of staticcheck itself.

**Comment by bshetty** [comment]
Many thanks for the mail. I first ran it against my team's code. Rabbit
against staticcheck to raise the issue.

I am surprised our code is so clean 🙄. But it should be right if you say
so.

Many thanks,
Bharat
