### ISSUE TITLE
U1000 flags function that's only unused on current GOOS

### ISSUE THREAD

**Issue by danderson** [dominikh/go-tools#695]
staticcheck flagged a U1000 unused function on `listPortsNetstat` of https://github.com/tailscale/tailscale/blob/master/portlist/netstat.go .

For GOOS=linux, staticcheck is correct, that function is unused. However, it's used for all other GOOS values (notably darwin and windows), via build-tagged source files (https://github.com/tailscale/tailscale/blob/master/portlist/portlist_darwin.go , https://github.com/tailscale/tailscale/blob/master/portlist/portlist_windows.go , and https://github.com/tailscale/tailscale/blob/master/portlist/portlist_other.go)

I considered fixing this by adding a `// +build !linux` to netstat.go. This is strictly correct, but it means that we can't run the netstat unit tests on GOOS=linux, even though it provides valuable test coverage on our main development machines.

IMO, it would be better if staticcheck could figure out that code is used on _some_ platform, even if it's unused on the current one.

Version infos for various tools:

```
$ staticcheck -debug.version
staticcheck 2019.2.3

Compiled with Go version: go1.13.7
Main module:
	honnef.co/go/tools@v0.0.1-2019.2.3 (sum: h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)

$ go version
go version go1.13.7 linux/amd64

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dave/.cache/go-build"
GOENV="/home/dave/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dave/hack/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dave/tail/oss/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build794878447=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dominikh** [comment]
> I considered fixing this by adding a `// +build !linux` to netstat.go. This is strictly correct, but it means that we can't run the netstat unit tests on GOOS=linux, even though it provides valuable test coverage on our main development machines.

You could move just that function to a new file, with the appropriate build tag. The only other alternative right now is using `//lint:ignore`.

In general, this is a known issue (#48) and affects any use of build tags. 

> IMO, it would be better if staticcheck could figure out that code is used on some platform, even if it's unused on the current one.

This is not viable with the current infrastructure, because we would have to analyze packages with all possible combinations of build tags (GOOS, GOARCH, custom build tags), and the amount of combinations is simply too large (yes, that contradicts what I said in #48, I didn't know any better at the time.)

I am currently planning a redesign of the _unused_ check to address some of its other issues. I'll keep the build tag issue in mind and try to design something that handles build tags better. Failing that, the alternative would be to explicitly specify all desired combinations of build tags. This might also benefit other checks that depend on the current platform, such as alignment checks for atomics.

I'm going to close this issue in favour of the existing one.
