### ISSUE TITLE
staticcheck verbose mode

### ISSUE THREAD

**Issue by disconnect3d** [dominikh/go-tools#699]
Hey,

It would be nice if staticcheck had a `-verbose` flag that would show all files that are scanned, similarly e.g. to `gosec`.

This might be helpful when checking out a repository with a complex build system (e.g. conditional compilation of files based on architecture or some tags).

**Comment by dominikh** [comment]
What's the desired purpose of such a flag? Is it to verify that all files in a project were analyzed? An ordinary `print what we're doing` flag likely wouldn't fulfill that requirement, because staticcheck heavily relies on caching and may not look at all files. We could of course print a list of files we _would have to_ look at were the cache empty, but such output would not qualify as "verbose output" in my opinion.

Printing which files belong to a given build may not be staticcheck's job at all. One could argue that this constitutes a different kind of analysis, one that can be implemented with the appropriate calls to `go list`.

**Comment by dominikh** [comment]
Closing for lack of feedback.
