### ISSUE TITLE
release.2020.1 branch still throws SA1019 for protobuf

### ISSUE THREAD

**Issue by blocknonip** [dominikh/go-tools#754]
- The output of 'staticcheck -version'
```
$ GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@release.2020.1
go: found honnef.co/go/tools/cmd/staticcheck in honnef.co/go/tools v0.0.1-2020.1.4

$ staticcheck --version
staticcheck 2020.1.4
```
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
$ staticcheck -debug.version
staticcheck 2020.1.4

Compiled with Go version: go1.14.2
Main module:
        honnef.co/go/tools@v0.0.1-2020.1.4 (sum: h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d (sum: h1:/iIZNFGxc/a7C3yWjGcnboV+Tkc7mxr+p6fDztwoxuM=)
```
- The output of 'go version'
```
$ go version
go version go1.14.2 darwin/amd64
```

- Exactly which command you ran
```
$ staticcheck ./...
...
common/parse/gateway/gateway_up.go:7:2: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
common/parse/gateway/gateway_up_test.go:13:2: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
```

I don't have a public repo that I can immediately share, but I imagine this is easily reproducible using the github protobuf dependency.

**Comment by dominikh** [comment]
Please note that we only automatically ignore the deprecation warning _in code generated by protoc-gen-go_. We do not ignore _all_ imports of the deprecated package. If your own code uses the deprecated package, then you should move to using the replacement for the deprecated package. And you can manually ignore the warning with a `//lint:ignore` directive.

Since you didn't share any code I cannot tell if these files are supposed to be generated by protoc-gen-go or not.

**Comment by blocknonip** [comment]
Ah, then I misunderstood the intent of the whitelist. The code in question is non-generated code that uses code currently generated by `protoc-gen-go` in a 3rd party package.

I will close this and leave that rule disabled. Thanks.
