### ISSUE TITLE
simple or quickfix: replace strings.Replace with strings.ReplaceAll where applicable

### ISSUE THREAD

**Issue by Zamiell** [dominikh/go-tools#755]
Greetings to the maintainers and thanks for the excellent linter(s).

I propose that the `simple` linter should warn on the following code:

```
fmt.Println(strings.Replace("oink oink oink", "oink", "moo", -1)) // Prints "moo moo moo"
```

And recommend converting it to:

```
fmt.Println(strings.ReplaceAll("oink oink oink", "oink", "moo")) // Prints "moo moo moo"
```

Hopefully you agree. = )

**Comment by martisch** [comment]
Similar could be done for `strings` and `bytes` `SplitN` function.

**Comment by mwat56** [comment]
Considering (a) that there was probably a reason the programmer chose the `Replace(…)` variant and (b) that `ReplaceAll(…)` is just a shell around `Replace(…)` the suggested warning/recommendation seem counterproductive to me.
Both, the additional test and the implemented recommendation, seem to be just a waste of electricity and runtime.

**Comment by martisch** [comment]
Sometimes the reason `Replace` is used is that the programmer does not know about `ReplaceAll`. This sounds fine to me for the quickfix suggested category.  I find reading `ReplaceAll` to be better recognizeable in code for its meaning. Im not sure how runtime is wasted when midstack inlining is involved unless this is about the staticchecker itself. 

Existing https://staticcheck.io/docs/checks#S1003 is I think similar in that `strings.Contains` is "just" a shell around `strings.Index` too.

**Comment by mwat56** [comment]
> Existing https://staticcheck.io/docs/checks#S1003 is I think similar in that `strings.Contains` is "just" a shell around `strings.Index` too.

Indeed, and it's just a bad as the current suggestion. IMHO one should _never_ recommend using a "shell" instead of the "original". But I acknowledge that opinions differ.

**Comment by dominikh** [comment]
> Both, the additional test and the implemented recommendation, seem to be just a waste of electricity and runtime.

For staticcheck, we do not care about minimizing the use of electricity, and we do not need to worry about miniscule differences in runtime, as the difference would be too small to even measure.

In terms of the runtime of the compiled program, the wrapper will very likely be inlined by the compiler, meaning there will be no difference whatsoever.

> Considering (a) that there was probably a reason the programmer chose the Replace(…) variant

Linters would be out of a job if programmers always had a reason for the things they wrote. Programmers are often not aware of simpler solutions.

> IMHO one should never recommend using a "shell" instead of the "original". But I acknowledge that opinions differ.

Opinions obviously differ, as otherwise these helper functions wouldn't exist. Most people seem to agree that `string.Contains(a, b)` is a lot easier to understand than `string.Index(a, b) != -1`. strings.ReplaceAll may fall into the same category.

Whether this is a check for `simple` or `quickfix` needs to be decided still, though I'm leaning towards `quickfix`.

**Comment by mwat56** [comment]
> For staticcheck, we do not care about minimizing the use of electricity, and we do not need to worry about miniscule differences in runtime, as the difference would be too small to even measure.

Well, I – respectfully – disagree. Both, a single user calling `staticcheck` several times and the sum of many users combined, can amount to a quite measurable time and energy consumption. And trying to save energy should always be one of the goals to life up to.

> In terms of the runtime of the compiled program, the wrapper will very likely be inlined by the compiler, meaning there will be no difference whatsoever.

Ah, but even it that were true, the compiler would need to perform some (otherwise unnecessary) computations which amounts to both, runtime and energy consumption.

> > Considering (a) that there was probably a reason the programmer chose the Replace(…) variant
> 
> Linters would be out of a job if programmers always had a reason for the things they wrote. Programmers are often not aware of simpler solutions.

Agreed. I just don't think that "simpler" is always "better".

However, we seem to diverge … It's your program so it's ultimately your decision. I just grew up programming in a time (40 years ago) when my first computer had 1 KB RAM and every single byte was valuable. Networking was expensive (not only the hardware but the telecom fees as well) and hence to be kept to the least amount of transfer time possible. So 'till today I cringe whenever I see something that – to me – seems to be a waste of resources (RAM, CPU, bandwidth, and energy).

**Comment by Zamiell** [comment]
> Similar could be done for strings and bytes SplitN function.

Fantastic, yes!

> Most people seem to agree that string.Contains(a, b) is a lot easier to understand than string.Index(a, b) != -1. strings.ReplaceAll may fall into the same category.

Indeed! I think it is certainly easier to understand. Otherwise, a naive programmer would have to google the "Replace" documentation and look up what the "-1" is supposed to mean. Which is exactly what I did before opening this issue, and was annoyed. ;)

**Comment by mwat56** [comment]
> [...]
> a naive programmer would have to google the "Replace" documentation and look up what the "-1" is supposed to mean.

Well, that programmer should probably change to a more capable editor. For example, in VSCode I just have to press `F12` on a function and my editor jumps to the source code implementation of that very function including its documentation. 😉

And the [documentation](https://golang.org/pkg/) should always be available while programming; no need for Google at all …

**Comment by Zamiell** [comment]
@dominikh This issue still has the "needs-decision" tag. Are we any closer to reaching a decision? And is someone interested in doing a PR? I took a look at the code, but it is a bit over my head.

**Comment by dominikh** [comment]
@Zamiell it will likely go in the `quickfix` category, not `simple`. And that category doesn't exist yet. There isn't really anything anyone could contribute at this point. This will be something I'm going to work on in 2021.

**Comment by Zamiell** [comment]
Ok, thanks.

**Comment by Zamiell** [comment]
Thank you dom!!!

**Comment by dominikh** [comment]
Note that this is only a quickfix, which means that running `staticcheck` on the command line won't make these suggestions. Currently, nothing is making use of quickfixes, but the plan is to integrate them with gopls. That might still take a while, especially because gopls is currently trying to become stable, which precludes adding new features.
