### ISSUE TITLE
staticcheck: False negative for SA5011 – Possible nil pointer dereference

### ISSUE THREAD

**Issue by golopot** [dominikh/go-tools#788]
#### Code:

```go
package main

import (
	"fmt"
	"math/rand"
	"time"
)

type Foo struct {
	a int
}

func getFoo() *Foo {
	rand.Seed(time.Now().UTC().UnixNano())

	if rand.Intn(2) == 0 {
		return nil
	}

	return &Foo{}
}

func main() {
	foo := getFoo()
	fmt.Println(foo.a) // Expects a "Possible nil pointer dereference" warning here.
}
```

#### Expected:

There should be a warning for the line `fmt.Println(foo.a)` with "SA5011 – Possible nil pointer dereference"

#### Actual:

No warning.

#### Envs:

```console
$ staticcheck -version
staticcheck 2020.1.4

$ staticcheck -debug.version
staticcheck 2020.1.4

Compiled with Go version: go1.14.1
Main module:
        honnef.co/go/tools@v0.0.1-2020.1.4 (sum: h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d (sum: h1:/iIZNFGxc/a7C3yWjGcnboV+Tkc7mxr+p6fDztwoxuM=)

$ go version
go version go1.14.4 linux/amd64

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jchn/.cache/go-build"
GOENV="/home/jchn/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jchn/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jchn/go/src/test-interface/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"


```

**Comment by dominikh** [comment]
SA5011 doesn't apply inter-procedural analysis. It is only concerned with control flow within a single function, and it checks for a very specific pattern: a pointer that is both dereferenced unconditionally, and checked against nil somewhere else.

While checking for your example would be doable, and might find genuine bugs, it would also be prone to false positives due to contracts we cannot understand. For example, `getFoo` might only return nils if it's Saturday, and we never call `getFoo` on Saturdays… In other words, the behavior of `getFoo` and `main` may be linked via any kind of state – global variables, struct fields, other bizarre implied contracts.

For better or worse, staticcheck errs on the side of false negatives: we strive never to flag correct code, but we may miss bugs.

But for what it is worth, your pattern isn't very common in Go, at least not in that form. In Go, we don't rely very much on checking for nil pointers. Instead, `getFoo` should also return an `error` or a `bool` indicating some form of failure or success, which makes it much more obvious that something needs to be checked, and much less likely to forget to check.
