### ISSUE TITLE
simple: error on single file but not its whole-package (or whole-dir)

### ISSUE THREAD

**Issue by metaleap** [dominikh/go-tools#81]
Single-file, errors out:

    [20:11 me ~/.../github.com/metaleap]$ gosimple go-util-str/str.go 
    /home/me/c/go/src/github.com/metaleap/go-util-str/str.go:264:10: undeclared name: Buffer
    /home/me/c/go/src/github.com/metaleap/go-util-str/str.go:379:18: undeclared name: Buffer
    2017/04/10 20:12:02 couldn't load packages due to errors: adhoc

But on the whole-dir, it works:

    [20:11 me ~/.../github.com/metaleap]$ gosimple ./go-util-str/
    go-util-str/str.go:361:6: should use strings.Contains(s, "  ") instead (S1003)

Same with whole-package given as import-path:

    [20:12 me ~/.../github.com/metaleap]$ gosimple github.com/metaleap/go-util-str
    go-util-str/str.go:361:6: should use strings.Contains(s, "  ") instead (S1003)

Fetch the repo used in the above if in need of repro

**Comment by shurcooL** [comment]
That looks like "working as intended" to me.

From https://github.com/dominikh/go-tools/tree/master/cmd/gosimple#usage:

> Invoke `gosimple` with one or more filenames, a directory, or a package named by its import path.

When invoked with one or more filenames, it treats it as an ad-hoc package with only those files.

This is consistent with `go build`, which is documented at https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies:

> If the arguments to build are a list of .go files, build treats them as a list of source files specifying a single package.

`str.go` by itself does not define `Buffer`, so there's a package build error.

Same error happens if you use `go build` with `str.go` filename only:

```
$ go build str.go 
# command-line-arguments
./str.go:264: undefined: Buffer
./str.go:379: undefined: Buffer
```

**Comment by metaleap** [comment]
I see, if that's "idiomatic" so to speak then I'm fine with that! Thought that might have been unintended..
