### ISSUE TITLE
Check memory usage of staticcheck on github.com/fyne-io/fyne

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#825]
People [have reported OOMs](https://github.com/fyne-io/fyne/pull/1308) in Travis.

**Comment by Jacalz** [comment]
I think you can close this. Our issues has gone away after some changes in Fyne in combination the latest staticcheck releases.  Thanks for making the best static analysis available 🙂

**Comment by dominikh** [comment]
That's good to hear, but now I'm even more curious to find out what specific change in Fyne fixed it. September 2020 to January 2021 should be a small enough range to be able to bisect this nicely.

I'll definitely still look into this at some point.

**Comment by Jacalz** [comment]
Ah, I see. Sorry, I should have attached a link to the changes. It was largely fixed by https://github.com/fyne-io/fyne/pull/1638 which changed the bundled (or embedded if you may) resources from being `[]byte` to `string`. This was initially brought up in https://github.com/fyne-io/fyne/pull/1436 due to the severe memory usage issues that I had reported to `gopls`. It is also becoming much less of an issue now that we have `go:embed` in Go 1.16, though I guess there might still be some cases where large slices could cause excessive memory usage.

**Comment by dominikh** [comment]
Ah, I see. I am going to close this, then. A large portion of the memory usage seems to be in go/ast and go/types. Our IR is piling on even more memory usage, but that's indirectly tracked by #618. And you're right about `go:embed` making this issue less important.

Thanks for the update.
