### ISSUE TITLE
simple: flag ranging over []rune(s) when ranging over s works

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#90]
`for _, r := range []rune(s)` can be rewritten as `for _, r := range s` with identical results, less code, and fewer memory allocations. The optimization cannot be made if the index is used (ranging over string yields byte indices). The optimization should only be made for `range []rune(s)`, not `rs := []rune(s); range rs`.

**Comment by shurcooL** [comment]
This check is inspired by suboptimal Go code I wrote 3 years ago:

https://github.com/shurcooL/sanitized_anchor_name/blame/79c90efaf01eddc01945af5bc1797859189b830b/main.go#L16

For reference, the reason I wrote `for _, r := range []rune(text) {` instead of `for _, r := range text {` is because I wasn't aware at the time that ranging over `string` would give me `rune`s rather than `byte`s. So, this check would've been helpful to me back then (and for everyone else in the future who runs into this).

**Comment by dominikh** [comment]
Now, should this check be in gosimple (it's simpler code), staticcheck (it's more efficient code), or in both?

**Comment by bradleyfalzon** [comment]
I like to think (although it's not alway true) staticcheck can break the build, gosimple won't.

**Comment by shurcooL** [comment]
Is the reason to put it in both, rather than just gosimple, so that users who don't care about simplifying code but do care about correctness/performance and run `staticcheck` only still get notified about it?

**Comment by dominikh** [comment]
@bradleyfalzon True for all but the performance category. @shurcooL Yes.

**Comment by shurcooL** [comment]
In that case, both makes sense to me. The message can differ between the tools to put focus on what's relevant to the tool (simplifying code vs reducing allocations).

**Comment by dominikh** [comment]
> The optimization should only be made for range []rune(s), not rs := []rune(s); range rs.

We can actually make the suggestion even in that case, as long as `rs` is only used for ranging over.
