### ISSUE TITLE
feature: special messages for soon to be deprecated io/ioutil functions.

### ISSUE THREAD

**Issue by selahaddinh** [dominikh/go-tools#919]
As you may know, Go 1.16 is deprecating io/ioutil.
https://tip.golang.org/doc/go1.16
I think it will be really helpful if staticcheck prints the new locations for deprecated functions along side the error message for deprecation, which are listed below.

```
The io/ioutil package has turned out to be a poorly defined and hard to understand collection of things. 
All functionality provided by the package has been moved to other packages. 
The io/ioutil package remains and will continue to work as before, but we encourage new code to use the new definitions in the io and os packages. 
Here is a list of the new locations of the names exported by io/ioutil:

Discard => io.Discard
NopCloser => io.NopCloser
ReadAll => io.ReadAll
ReadDir => os.ReadDir (note: returns a slice of os.DirEntry rather than a slice of fs.FileInfo)
ReadFile => os.ReadFile
TempDir => os.MkdirTemp
TempFile => os.CreateTemp
WriteFile => os.WriteFile
```

**Comment by dominikh** [comment]
Staticcheck already has a check that flags uses of deprecated code, when code has been annotated as deprecated. The io/ioutil package hasn't been annotated as such, which is why we don't flag it.

I am not sure we _should_ flag it, either. There is no immediate need to migrate away from io/ioutil in existing code, and we don't have a way of only flagging newly written code. This is different from most deprecated code, where there's usually some harm to continued use.

We can reconsider this in a couple of years, when there has been more time since io/ioutil's deprecation. At that point, the correct way forward would likely be to annotate io/ioutil directly.
