### ISSUE TITLE
simple: Import(".", d, m) -> ImportDir(d, m) for go/build.

### ISSUE THREAD

**Issue by dmitshur** [dominikh/go-tools#92]
Depending on the outcome of #91, here's another similar potential check, expressed in `gofmt -r` syntax:

```
Import(".", d, m) -> ImportDir(d, m)
```

It should apply to `go/build.Import` and `go/build.Context.Import` calls where first `path` argument is known to be have "." value.

**Comment by dominikh** [comment]
Does this actually depend on #91? Are there instances where one would prefer `Import(".", d, m)` over `ImportDir(d, m)`?

**Comment by shurcooL** [comment]
I've seen a lot, and I mean a _lot_, of existing code that does `Import(".", d, m)` for some reason. Maybe it predates `ImportDir` existing, or maybe there's another reason, I don't know.

I assume the only reasons people use `Import(".", d, m)` is when they don't know about `ImportDir` being equivalent, or when they have it close to other code that calls `Import` with first parameter not ".".

**Comment by shurcooL** [comment]
Following up with more information here, which will hopefully aid in making a decision.

> Maybe it predates `ImportDir` existing

Both `Import` and `ImportDir` (in function and method variants) were added together in Go 1.0:

```
pkg go/build, func Import(string, string, ImportMode) (*Package, error)
pkg go/build, func ImportDir(string, ImportMode) (*Package, error)
pkg go/build, method (*Context) Import(string, string, ImportMode) (*Package, error)
pkg go/build, method (*Context) ImportDir(string, ImportMode) (*Package, error)
```
_(Source: https://raw.githubusercontent.com/golang/go/master/api/go1.txt.)_

So that rules out the `Import` predates `ImportDir` hypothesis.

> I've seen a lot, and I mean a _lot_, of existing code that does `Import(".", d, m)`

This isn't the case in GOROOT:

```
Searching 4128 files for "Import(".", "

/usr/local/go/src/go/build/build.go:
  433  // the named directory.
  434  func (ctxt *Context) ImportDir(dir string, mode ImportMode) (*Package, error) {
  435: 	return ctxt.Import(".", dir, mode)
  436  }
  437  

/usr/local/go/src/go/build/build_test.go:
   88  
   89  func TestEmptyFolderImport(t *testing.T) {
   90: 	_, err := Import(".", "testdata/empty", 0)
   91  	if _, ok := err.(*NoGoError); !ok {
   92  		t.Fatal(`Import("testdata/empty") did not return NoGoError.`)
   ..
   95  
   96  func TestMultiplePackageImport(t *testing.T) {
   97: 	_, err := Import(".", "testdata/multi", 0)
   98  	mpe, ok := err.(*MultiplePackageError)
   99  	if !ok {

3 matches across 2 files
```

But in golang.org/x/tools, where I thought I saw "a lot" of existing code doing it, there were actually 0 hits:

```
Searching 641 files for "Import(".", "

0 matches
```

It turns out I misremembered. Digging some more into it, _maybe_ what I saw instead was code like this:

```
build.Import(dir, ".", 0)
```

Which is weird but not the same.

It's also possible that what I saw was a lot of _errors_ related to finding "." import path relative to an absolute directory, not Go code that does `Import(".", d, m)`. This was in the context of https://go-review.googlesource.com/c/37768/.

### Conclusion

In any case, after doing some looking around now, I don't see any evidence of lots of existing code doing `Import(".", d, m)`. So I think it's a relatively safe check to suggest (one that won't have false positives).

**Comment by dominikh** [comment]
I've decided against this. I don't find ImportDir to be superior to Import. Also, it will be moot very soon when people migrate to `go/packages` and stop using `go/build`.
