### ISSUE TITLE
cmd/unused: False negatives when private value are accessed in test files

### ISSUE THREAD

**Issue by hypirion** [dominikh/go-tools#94]
When test files contain a reference to a private value which is not used outside `_test.go` files, they are not considered unused. This can be annoying when you have whitebox tests.

For example:

```go
// foo.go
package foo

func bar(_ string) error {
	return nil
}
```

```go
//foo_test.go
package foo

import (
	"testing"
)

// verify that bar works on input.
func TestBar(t *testing.T) {
	err := bar("quux")
	if err != nil {
		t.Fatal(err)
	}
}
```

Without "foo_test.go", `bar` is registered as unused. With it, `bar` is considered used.

Would recommending to remove `bar` (or move it to `*_test.go`) be sensible here, or would this break something?

**Comment by mvdan** [comment]
Are you using `-tests=true`?

**Comment by dominikh** [comment]
This is essentially https://github.com/dominikh/go-unused/issues/9 and a feature request, not a false positive.

**Comment by dominikh** [comment]
This is unfortunately working as intended. It is, unfortunately, a common pattern for test helpers to be defined in non-test files; even the Go stdlib does this a fair bunch. This is even more the case once we look at build tags in general instead of just tests. Flagging those instances would go against common practice.

The recommended workaround is to run the check with -tests=false to ignore tests completely.
